ci: Add GHA workflows for linux tag builds (#2302)
Extend the workflows that do the linux push builds to do the tag builds
as well. The workflows are sufficient to replace the equivalent ones in
Drone and produce the same release artifacts. There are not separate
workflows for packaging deb/rpm archives as there are in Drone - that
is all taken care of in the single `build-linux.yaml` workflow.

A subsequent PR in the teleport repo will update `dronegen` to call the
`release-linux.yaml` workflow with appropriate parameters for each
build.

Drone duplicated a couple of builds - the amd64 and centos7 builds
ultimately called the same makefile targets for their builds. All amd64
builds are done on centos7 even if the workflow/pipeline was not named
with "centos7".

Issue: https://github.com/gravitational/teleport/issues/20729

Source-commit: gravitational/teleport.e@3badcee5b79a3288b24ee4580020466ce42735b0
Source-pull-requests: gravitational/teleport.e#2302

diff --git a/e/.github/workflows/build-linux.yaml b/e/.github/workflows/build-linux.yaml
--- a/e/.github/workflows/build-linux.yaml
+++ b/e/.github/workflows/build-linux.yaml
@@ -36,11 +36,34 @@ on:
         required: true
         type: string
 
+      save-artifacts:
+        description: "Should the build export the build artifacts"
+        required: false
+        type: boolean
+        default: false
+
       build-connect:
         description: "Should Teleport Connect be built"
         required: false
         type: boolean
         default: false
+
+      build-deb:
+        description: "Should a Debian package of the release be built"
+        required: false
+        type: boolean
+        default: false
+
+      build-rpm:
+        description: "Should a RPM package of the release be built"
+        required: false
+        type: boolean
+        default: false
+
+      arch:
+        description: "Architecture for OS package builds"
+        required: false
+        type: string
 
       builder:
         # This needs to be encoded as JSON, as parameters can opnly be strings, numbers
@@ -55,12 +78,23 @@ on:
         required: true
         type: string
 
+      environment:
+        description: |
+          GitHub Actions environment in which to run the build. Can be either
+          `promote` or `build`.
+        required: false
+        type: string
+        default: promote
+
 jobs:
   build-release-artifacts:
     permissions:
       contents: read
+      id-token: write # required for aws-actions/configure-aws-credentials for OIDC
 
     runs-on: ${{ fromJSON(inputs.builder) }}
+
+    environment: ${{ inputs.environment }}
 
     env:
       # GOMODCACHE and GOCACHE can be removed when we commit to the self-hosted
@@ -79,6 +113,16 @@ jobs:
             sudo apt install -y make
           fi
 
+      - name: Determine FIPS
+        id: determine-fips
+        env:
+          RELEASE_TARGET: ${{ inputs.release-target }}
+        run: |
+          case "$RELEASE_TARGET" in
+          *-fips) echo 'is-fips=true' ;;
+          *) echo 'is-fips=false' ;;
+          esac >> "$GITHUB_OUTPUT"
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
@@ -89,13 +133,29 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+      # Assume AWS role log into ECR
+      - name: Assume teleport build user AWS role
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: us-west-2
+          role-to-assume: arn:aws:iam::146628656107:role/tf-teleport-build-read-only-role-gha
+          role-session-name: "gha-build-linux-${{ github.run_number }}"
+          role-duration-seconds: 3600
+
+      # Log into ECR to raise rate limits, needed for the public.ecr.aws/gravitational/fpm
+      # image used for building .deb and .rpm files.
+      - name: Log into ECR
+        run: |
+          aws ecr-public get-login-password --region us-east-1 | \
+            docker login -u=AWS --password-stdin public.ecr.aws
+
       # The step can be removed when we commit to the self-hosted ARC runners,
       # as it runs with a consistent UID/GID and creates the directories with
       # the correct ownership. We still need this for the GitHub runners though.
       - name: Create cache directories with correct owner/group
         run: |
           sudo mkdir -p "$GOCACHE" "$GOMODCACHE"
-          sudo chown -Rf $(id -u):$(id -g) "$GOCACHE" "$GOMODCACHE"
+          sudo chown -Rf "$(id -u):$(id -g)" "$GOCACHE" "$GOMODCACHE"
 
       - name: Checkout Teleport
         uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
@@ -107,15 +167,131 @@ jobs:
           repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
           repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
 
-      - name: Build Release
+      # FIPS and Teleport Connect builds need VERSION set in the environment as those
+      # builds do not go through the top-level teleport Makefile, which sets it for
+      # other builds.
+      - name: Set Version
         run: |
-          make -C build.assets ${{ inputs.release-target }}
+          VERSION=$(grep -oP '^VERSION=\K.*' Makefile)
+          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
+
+      - name: Build Release
+        env:
+          RELEASE: ${{ inputs.release }}
+          RELEASE_TARGET: ${{ inputs.release-target }}
+          RELEASE_DIR: ${{ github.workspace }}/build/artifacts
+        run: |
+          mkdir -p "$RELEASE_DIR" # TODO(camscale): Move -p to Makefile
+          make -C build.assets "$RELEASE_TARGET"
+          # CentOS7 builds are used for all Linux AMD64 targets, but are also named with a
+          # centos7 tag too.
+          # TODO(camscale): Move this naming to the Makefile
+          if [ "$RELEASE_TARGET" = 'release-amd64-centos7' ]; then
+            cp "build/artifacts/teleport-v${VERSION}-linux-amd64-bin.tar.gz" \
+               "build/artifacts/teleport-v${VERSION}-linux-amd64-centos7-bin.tar.gz"
+            if [ "$RELEASE" = 'enterprise' ]; then
+              cp "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-bin.tar.gz" \
+                 "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-centos7-bin.tar.gz"
+            fi
+          elif [ "$RELEASE_TARGET" = 'release-amd64-centos7-fips' ]; then
+            # FIPS builds end up in e/build/artifacts as $RELEASE_DIR does not pass through
+            # to the docker build.
+            cp "e/build/artifacts/teleport-ent-v${VERSION}-linux-amd64-fips-bin.tar.gz" build/artifacts
+            cp "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-fips-bin.tar.gz" \
+               "build/artifacts/teleport-ent-v${VERSION}-linux-amd64-centos7-fips-bin.tar.gz"
+          fi
 
       - name: Build Teleport Connect
         if: inputs.build-connect
         run: |
-          # VERSION is only set from the top-level Makefile. We need it to be
-          # set so that the build artifacts are named correctly.
-          VERSION=$(grep -oP '^VERSION=\K.*' Makefile)
           make -C build.assets teleterm VERSION="$VERSION"
           cp web/packages/teleterm/build/release/teleport-connect* build/artifacts
+
+      - name: Build Debian package
+        if: inputs.build-deb && !steps.determine-fips.outputs.is-fips
+        env:
+          ARCH: ${{ inputs.arch }}
+          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
+          OSS_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
+          RELEASE: ${{ inputs.release }}
+        run: |
+          make deb
+          # TODO(camscale): Move artifact copying to Makefile(s)
+          cp build/*.deb build/artifacts
+          if [ "$RELEASE" = 'enterprise' ]; then
+            cp e/build/*.deb build/artifacts
+          fi
+
+      - name: Build FIPS Debian package
+        if: inputs.build-deb && steps.determine-fips.outputs.is-fips
+        env:
+          ARCH: ${{ inputs.arch }}
+          FIPS: yes
+          RUNTIME: fips
+          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
+        run: |
+          make -C e deb
+          # TODO(camscale): Move artifact copying to Makefile(s)
+          cp e/build/*.deb build/artifacts
+
+      # TODO(camscale): Convert this step to use ./github/actions/load-gpg-key
+      - name: Extract RPM Signing Archive
+        if: inputs.build-rpm
+        env:
+          GPG_SIGNING_ARCHIVE: ${{ secrets.GPG_SIGNING_ARCHIVE }}
+          GNUPG_DIR: /tmp/gnupg
+        run: |
+          if [ -z "$GPG_SIGNING_ARCHIVE" ]; then
+            echo "GPG signing archive is unset or empty, aborting"
+            exit 1
+          fi
+          mkdir -m 0700 "$GNUPG_DIR"
+          echo "$GPG_SIGNING_ARCHIVE" | base64 -d | tar -xzf - --no-same-owner --no-overwrite-dir -C "$GNUPG_DIR"
+          chown -Rv "$(id -un):$(id -gn)" "$GNUPG_DIR"
+
+      - name: Build RPM package
+        if: inputs.build-rpm && !steps.determine-fips.outputs.is-fips
+        env:
+          ARCH: ${{ inputs.arch }}
+          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
+          OSS_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
+          RELEASE: ${{ inputs.release }}
+          GNUPG_DIR: /tmp/gnupg
+        run: |
+          make rpm
+          # TODO(camscale): Move artifact copying to Makefile(s)
+          cp build/*.rpm build/artifacts
+          if [ "$RELEASE" = 'enterprise' ]; then
+            cp e/build/*.rpm build/artifacts
+          fi
+
+      - name: Build FIPS RPM package
+        if: inputs.build-rpm && steps.determine-fips.outputs.is-fips
+        env:
+          ARCH: ${{ inputs.arch }}
+          FIPS: yes
+          RUNTIME: fips
+          ENT_TARBALL_PATH: ${{ github.workspace }}/build/artifacts
+          RELEASE: ${{ inputs.release }}
+          GNUPG_DIR: /tmp/gnupg
+        run: |
+          make -C e rpm
+          # TODO(camscale): Move artifact copying to Makefile(s)
+          cp e/build/*.rpm build/artifacts
+
+      - name: Checksum artifacts
+        run: |
+          cd build/artifacts
+          for f in *; do
+            [ -f "$f.sha256" ] && continue
+            shasum -a 256 "$f" > "$f.sha256"
+            cat "$f.sha256"
+          done
+
+      - name: Upload artifacts
+        if: inputs.save-artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: release
+          path: |
+            build/artifacts
