Support basic upgrade test (#3784)
* Add force run option

* Add update test

* Combine test as separate steps

* Remove do-teleport-updater-tests input

* Remove do-teleport-updater-tests input

* Add force command help

* Do package test if not upater

* Set initial teleport installation version

* Support sles12sp5 test

* Fix var name

* Fix version comparison

* Address feedback

- Add comment explaining systemctl check
- Move curl and awk installtion to updater specific step

Source-commit: gravitational/teleport.e@b74661b99d3af18f7a7ad48d9df1482e87d1694a
Source-pull-requests: gravitational/teleport.e#3784

diff --git a/e/.github/workflows/deploy-packages.yaml b/e/.github/workflows/deploy-packages.yaml
--- a/e/.github/workflows/deploy-packages.yaml
+++ b/e/.github/workflows/deploy-packages.yaml
@@ -459,7 +459,6 @@ jobs:
         env:
           RELEASE_CHANNEL: ${{ inputs.release-channel }}
           VERSION_CHANNEL: ${{ needs.deploy.outputs.component-version-channel }}
-          PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
         run: |
           # Install teleport based off of instructions from https://goteleport.com/docs/installation/#linux
           # This is designed to be changed as little as possible from the source
@@ -483,17 +482,19 @@ jobs:
 
           echo "Package files:"
           apt-file list "$PACKAGE_TO_TEST"
+
+      # do teleport package tests
       - name: Install the package
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         env:
           PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
         run: |
           sudo apt-get install -y "$PACKAGE_TO_TEST=$PACKAGE_VERSION"
       - name: Log Teleport version
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         run: teleport version
       - name: Verify installed Teleport version matches provided artifact version
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         env:
           ARTIFACT_TAG: ${{ inputs.artifact-tag }}
         run: |
@@ -502,6 +503,53 @@ jobs:
             echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version (${ARTIFACT_TAG#v})!!!"
             exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
           fi
+
+      # do teleport updater tests
+      - name: Set initial Teleport installation version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        env:
+          # Arbitrary teleport version for initial teleport installation
+          TELEPORT_TAG: v13.4.0
+        run: echo "TELEPORT_VERSION=${TELEPORT_TAG#v}" >> "$GITHUB_ENV"
+      - name: Install the teleport and teleport updater packages
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: sudo apt-get install -y "teleport-ent=$TELEPORT_VERSION" "teleport-ent-updater=$PACKAGE_VERSION"
+      - name: Log Teleport version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: teleport version
+      - name: Verify installed Teleport version matches provided artifact version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          REPORTED_VERSION=$(teleport version --raw)
+          if [ "$REPORTED_VERSION" != "$TELEPORT_VERSION" ]; then
+            echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version ($TELEPORT_VERSION)!!!"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+      - name: Test update
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          TARGET_VERSION=$(curl https://updates.releases.teleport.dev/v1/stable/cloud/version)
+          echo 'apt' > /etc/teleport-upgrade.d/installer
+          teleport-upgrade force
+          REPORTED_VERSION=$(teleport version --raw)
+          if [ "$REPORTED_VERSION" != "${TARGET_VERSION#v}" ]; then
+            echo "Reported version ($REPORTED_VERSION) does not match target version (${TARGET_VERSION#v})"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+      - name: Test system update
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          BEFORE_UPGRADE=$(teleport version --raw)
+          # Perform a system update.
+          # The teleport version is expected to be locked
+          apt-mark hold teleport-ent-updater
+          apt-get upgrade -y
+          AFTER_UPGRADE=$(teleport version --raw)
+          if [ "$BEFORE_UPGRADE" != "$AFTER_UPGRADE" ]; then
+            echo "Before upgrade version ($BEFORE_UPGRADE) does not match after upgrade version ($AFTER_UPGRADE))"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+
   yum-rhel-smoke-test:
     name: Test packages deployed to YUM repo on RHEL
     if: inputs.repo-type == 'yum' && inputs.package-to-test != ''
@@ -512,7 +560,7 @@ jobs:
       fail-fast: false
       matrix:
         # Multiple images are used to test for the ever recurring libc version issue
-        container-image: 
+        container-image:
           - centos:7
           # These are the closest we can easily get to rhel 7/8/9
           - registry.access.redhat.com/ubi7:7.9
@@ -568,7 +616,6 @@ jobs:
         env:
           RELEASE_CHANNEL: ${{ inputs.release-channel }}
           VERSION_CHANNEL: ${{ needs.deploy.outputs.component-version-channel }}
-          PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
         run: |
           # Install teleport based off of instructions from https://goteleport.com/docs/installation/#linux
           # This is designed to be changed as little as possible from the source
@@ -590,17 +637,19 @@ jobs:
 
           echo "Package files:"
           repoquery -l "$PACKAGE_TO_TEST-$PACKAGE_VERSION"
+
+      # do teleport package tests
       - name: Install the package
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         env:
           PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
         run: |
           sudo yum install -y "$PACKAGE_TO_TEST-$PACKAGE_VERSION"
       - name: Log Teleport version
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         run: teleport version
       - name: Verify installed Teleport version matches provided artifact version
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         env:
           ARTIFACT_TAG: ${{ inputs.artifact-tag }}
         run: |
@@ -609,6 +658,52 @@ jobs:
             echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version (${ARTIFACT_TAG#v})!!!"
             exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
           fi
+
+      # do teleport updater tests
+      - name: Set initial Teleport installation version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        env:
+          # Arbitrary teleport version for initial teleport installation
+          TELEPORT_TAG: v13.4.0
+        run: echo "TELEPORT_VERSION=$(echo "${TELEPORT_TAG#v}" | sed 's/-/_/g')" >> "$GITHUB_ENV"
+      - name: Install the teleport and teleport updater packages
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: sudo yum install -y "teleport-ent-$TELEPORT_VERSION" "teleport-ent-updater-$PACKAGE_VERSION"
+      - name: Log Teleport version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: teleport version
+      - name: Verify installed Teleport version matches provided artifact version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          REPORTED_VERSION=$(teleport version --raw)
+          if [ "$REPORTED_VERSION" != "$TELEPORT_VERSION" ]; then
+            echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version ($TELEPORT_VERSION)!!!"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+      - name: Test update
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          TARGET_VERSION=$(curl https://updates.releases.teleport.dev/v1/stable/cloud/version)
+          echo 'yum' > /etc/teleport-upgrade.d/installer
+          teleport-upgrade force
+          REPORTED_VERSION=$(teleport version --raw)
+          if [ "$REPORTED_VERSION" != "${TARGET_VERSION#v}" ]; then
+            echo "Reported version ($REPORTED_VERSION) does not match target version (${TARGET_VERSION#v})"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+      - name: Test system update
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          BEFORE_UPGRADE=$(teleport version --raw)
+          # Perform a system update.
+          # The teleport version is expected to be locked
+          yum upgrade -y teleport-ent
+          AFTER_UPGRADE=$(teleport version --raw)
+          if [ "$BEFORE_UPGRADE" != "$AFTER_UPGRADE" ]; then
+            echo "Before upgrade version ($BEFORE_UPGRADE) does not match after upgrade version ($AFTER_UPGRADE))"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+
   zypper-suse-smoke-test:
     name: Test packages deployed to Zypper repo on SUSE
     # Zypper changes are deployed via yum logic which is why the repo type checks for "yum" here
@@ -699,27 +794,87 @@ jobs:
           rm "$GPG_KEY_PATH"
 
           sudo zypper addrepo --refresh --repo $(rpm --eval "https://${ZYPPER_REPO_DOMAIN_NAME}/$ID/$VERSION_ID/Teleport/%{_arch}/$RELEASE_CHANNEL/$VERSION_CHANNEL/teleport-zypper.repo")
+
       - name: Log package cache information
         env:
           PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
         run: |
           zypper search -s "$PACKAGE_TO_TEST"
+
+      # do teleport package tests
       - name: Install the package
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         env:
           PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
         run: |
           sudo zypper install -y "$PACKAGE_TO_TEST=$PACKAGE_VERSION"
       - name: Log Teleport version
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         run: teleport version
       - name: Verify installed Teleport version matches provided artifact version
-        if: inputs.do-teleport-package-tests
+        if: inputs.do-teleport-package-tests && inputs.package-to-test != 'teleport-ent-updater'
         env:
           ARTIFACT_TAG: ${{ inputs.artifact-tag }}
         run: |
           REPORTED_VERSION=$(teleport version --raw)
           if [ "$REPORTED_VERSION" != "${ARTIFACT_TAG#v}" ]; then
             echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version (${ARTIFACT_TAG#v})!!!"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+
+      # do teleport updater tests
+      - name: Install curl and awk dependencies
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          # Install teleport based off of instructions from https://goteleport.com/docs/installation/#linux
+          # This is designed to be changed as little as possible from the source
+          source /etc/os-release
+          VERSION_ID=$(echo $VERSION_ID | cut -d'.' -f1)
+          if [ "$VERSION_ID" == "12" ]; then
+            zypper addrepo --refresh http://download.opensuse.org/update/leap/15.4/sle/ sle
+          fi
+          zypper install -y curl gawk
+      - name: Set initial Teleport installation version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        env:
+          # Arbitrary teleport version for initial teleport installation
+          TELEPORT_TAG: v13.4.0
+        run: echo "TELEPORT_VERSION=$(echo "${TELEPORT_TAG#v}" | sed 's/-/_/g')-1" >> "$GITHUB_ENV"
+      - name: Install the teleport and teleport updater packages
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: zypper install -y "teleport-ent-$TELEPORT_VERSION" "teleport-ent-updater-$PACKAGE_VERSION"
+      - name: Log Teleport version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: teleport version
+      - name: Verify installed Teleport version matches provided artifact version
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          REPORTED_VERSION=$(teleport version --raw)-1
+          if [ "$REPORTED_VERSION" != "$TELEPORT_VERSION" ]; then
+            echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version ($TELEPORT_VERSION)!!!"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+      - name: Test update
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          TARGET_VERSION=$(curl https://updates.releases.teleport.dev/v1/stable/cloud/version)
+          echo 'zypper' > /etc/teleport-upgrade.d/installer
+          teleport-upgrade force
+          REPORTED_VERSION=$(teleport version --raw)
+          if [ "$REPORTED_VERSION" != "${TARGET_VERSION#v}" ]; then
+            echo "Reported version ($REPORTED_VERSION) does not match target version (${TARGET_VERSION#v})"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+      - name: Test system update
+        if: inputs.do-teleport-package-tests && inputs.package-to-test == 'teleport-ent-updater'
+        run: |
+          BEFORE_UPGRADE=$(teleport version --raw)
+          # Perform a system update.
+          # The teleport version is expected to be locked
+          zypper addlock teleport-ent-updater
+          zypper update -y
+          AFTER_UPGRADE=$(teleport version --raw)
+          if [ "$BEFORE_UPGRADE" != "$AFTER_UPGRADE" ]; then
+            echo "Before upgrade version ($BEFORE_UPGRADE) does not match after upgrade version ($AFTER_UPGRADE))"
             exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
           fi
diff --git a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
--- a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
+++ b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
@@ -19,6 +19,11 @@ agent_conf="${TELEPORT_AGENT_CONFIG:-/etc/teleport.yaml}"
 # to be used by tests for confirming the correct behavior of the installer.
 dry_run="yes"
 
+# running the teleport-upgrade command with force, will force a teleport upgrade.
+# this bypasses the schedule check and performs an upgrade. This is not recommended
+# and is only intended to be used for testing at the moment.
+force_run="no"
+
 cmd="${1:-none}"
 
 case "$cmd" in
@@ -32,6 +37,10 @@ case "$cmd" in
         echo "$self_version"
         exit 0
         ;;
+    force)
+        force_run="yes"
+        dry_run="no"
+        ;;
     help)
         cat <<EOF
 USAGE: $0 <command>
@@ -41,6 +50,7 @@ Tool for automatic upgrades of Teleport agents.
 Commands:
   run           check for and potentially apply a teleport upgrade.
   dry-run       check for new teleport version but do not upgrade.
+  force         performs an upgrade if an upgrade is available.
   version       print the current version of $0.
   help          show this help text.
 EOF
@@ -349,24 +359,28 @@ is_critical() {
 # do_reload_or_restart reloads or restarts teleport.service (depending on
 # restart_mode) if it's currently running.
 do_reload_or_restart() {
-    systemctl daemon-reload
-    # reload or restart the service if it's currently running
-    if [[ "$restart_mode" == "reload" ]]; then
-        log_info "gracefully restarting Teleport (if already running)"
-        # reload returns an error if the unit isn't active, and
-        # try-reload-or-restart is too recent of an addition for centos7
-        if systemctl is-active --quiet teleport.service; then
-            # we fall back to restart in case the reload fails, for example if
-            # the pidfile used for reloading is not valid; this can happen
-            # across the upgrade to the Teleport version that started locking
-            # the pidfile
-            systemctl reload teleport.service || systemctl try-restart teleport.service
+    # fail quietly when systemd is disabled. This is only relevant when testing
+    # in a container.
+    if systemctl status > /dev/null 2>&1; then
+        systemctl daemon-reload
+        # reload or restart the service if it's currently running
+        if [[ "$restart_mode" == "reload" ]]; then
+            log_info "gracefully restarting Teleport (if already running)"
+            # reload returns an error if the unit isn't active, and
+            # try-reload-or-restart is too recent of an addition for centos7
+            if systemctl is-active --quiet teleport.service; then
+                # we fall back to restart in case the reload fails, for example if
+                # the pidfile used for reloading is not valid; this can happen
+                # across the upgrade to the Teleport version that started locking
+                # the pidfile
+                systemctl reload teleport.service || systemctl try-restart teleport.service
+            fi
+        else
+            log_warn "ungracefully restarting Teleport (if already running), sessions will be ungracefully cut"
+            # restart will eventually terminate the whole cgroup and then start
+            # Teleport again
+            systemctl try-restart teleport.service
         fi
-    else
-        log_warn "ungracefully restarting Teleport (if already running), sessions will be ungracefully cut"
-        # restart will eventually terminate the whole cgroup and then start
-        # Teleport again
-        systemctl try-restart teleport.service
     fi
 }
 
@@ -495,6 +509,16 @@ else
 fi
 
 restart_mode="$(get_conf restart-mode reload)"
+
+# force run bypasses the schedule check and performs the update
+if [[ "$force_run" == "yes" ]]; then
+    if ! do_upgrade; then
+        log_warn "upgrade attempt failed for $package_name=$target_version."
+        exit 1 
+    fi
+    exit 0
+fi
+
 if is_critical; then
     restart_mode=restart
     log_info "upgrade is marked as critical, will be attempted without checking maintenance window."
