Fixed zypper smoke tests (#1921)
Source-commit: gravitational/teleport.e@f47a681177a60859e0a6fd6a54f1ac8b29fddf3b
Source-pull-requests: gravitational/teleport.e#1921

diff --git a/e/.github/workflows/deploy-packages.yaml b/e/.github/workflows/deploy-packages.yaml
--- a/e/.github/workflows/deploy-packages.yaml
+++ b/e/.github/workflows/deploy-packages.yaml
@@ -477,9 +477,6 @@ jobs:
           - registry.access.redhat.com/ubi7:7.9
           - registry.access.redhat.com/ubi8:8.7
           - registry.access.redhat.com/ubi9:9.1
-          # SUSE Linux Enterprise Edition
-          - registry.suse.com/suse/sles12sp5:latest # The other tags are too specific so latest is used instead
-          - registry.suse.com/bci/bci-base:15.5
     container:
       image: ${{ matrix.container-image }}
     defaults:
@@ -546,6 +543,115 @@ jobs:
       - name: Log package cache information
         run: |
           yum --showduplicates list available ${{ inputs.package-to-test }}
+      - name: Verify installed Teleport version matches provided artifact version
+        env:
+          ARTIFACT_TAG: ${{ inputs.artifact-tag }}
+        run: |
+          REPORTED_VERSION=$(teleport version --raw)
+          if [ "$REPORTED_VERSION" != "${ARTIFACT_TAG#v}" ]; then
+            echo "Installed version ($REPORTED_VERSION) does not match uploaded artifact version (${ARTIFACT_TAG#v})!!!"
+            exit 406  # Picking this number as Googling "error code 406" will show that it is a "not acceptable" error
+          fi
+  zypper-suse-smoke-test:
+    name: Test packages deployed to Zypper repo on SUSE
+    # Zypper changes are deployed via yum logic which is why the repo type checks for "yum" here
+    if: inputs.repo-type == 'yum' && inputs.package-to-test != ''
+    needs: deploy
+    runs-on: ubuntu-latest
+    # A container is used here to maintain consistency in the testing methodology for both APT, YUM, and Zypper
+    strategy:
+      fail-fast: false
+      matrix:
+        # Multiple images are used to test for the ever recurring libc version issue
+        container-image: 
+          # SUSE Linux Enterprise Edition
+          - registry.suse.com/suse/sles12sp5:latest # The other tags are too specific so latest is used instead
+          - registry.suse.com/bci/bci-base:15.5
+    container:
+      image: ${{ matrix.container-image }}
+    defaults:
+      run:
+        shell: bash
+    steps:
+      # Note: These values are intentionally hard-coded here to prevent false positives or negatives due
+      #       to a value in one of our code/IaC repos changing without the change propegating everywhere.
+      - name: Derive and set Github environment-specific variables for production
+        if: inputs.environment == 'production' || inputs.environment == 'promote'
+        run: |
+          echo "ZYPPER_REPO_DOMAIN_NAME=zypper.releases.teleport.dev" >> "$GITHUB_ENV"
+          echo "FORCE_INSTALL_PROD_PUBLIC_KEY=false" >> "$GITHUB_ENV"
+      - name: Derive and set Github environment-specific variables for development
+        if: inputs.environment == 'staging' || inputs.environment == 'build'
+        run: |
+          echo "ZYPPER_REPO_DOMAIN_NAME=zypper.releases.development.teleport.dev" >> "$GITHUB_ENV"
+          # This is required as the RPMs are signed by the prod key, not the dev key
+          # Without this zypper will fail due to a signing key mismatch
+          echo "FORCE_INSTALL_PROD_PUBLIC_KEY=true" >> "$GITHUB_ENV"
+      - name: Log set variables
+        run: |
+          echo "Set variables:"
+          env
+      - name: Setup for package install
+        env:
+          ARTIFACT_TAG: ${{ inputs.artifact-tag }}
+        run: |
+          # The container images are missing a couple of minor things needed for the install instructions
+          # on the downloads page
+          # sudo is not available in the image, so create a simple do-nothing script to replace it
+          SUDO_PATH="/usr/bin/sudo"
+          echo '$@' > "$SUDO_PATH"
+          chmod +x "$SUDO_PATH"
+          sudo echo "Running this with pseudo-sudo"
+
+          # Add the prod signing key specifically if required in a dev context to deal with prod-signed RPMs
+          # This logic is required because the SLES containers do not have curl, wget, or pre-existing package
+          # repos available. RPM also seems to have some sort of root CA trust issue as well, despite openssl
+          # working.
+          if $FORCE_INSTALL_PROD_PUBLIC_KEY; then
+            GPG_KEY_PATH="/tmp/teleport.gpg"
+            openssl s_client -quiet -connect zypper.releases.teleport.dev:443 -servername zypper.releases.teleport.dev <<EOF 2>/dev/null | sed '1,/^\r$/d' > "$GPG_KEY_PATH"
+            GET /gpg HTTP/1.0
+            Host: zypper.releases.teleport.dev
+
+            EOF
+            rpm --import "$GPG_KEY_PATH"
+            rm "$GPG_KEY_PATH"
+          fi
+
+          # Set the package version
+          # Note that if we ever republish a tag then the `-1` at the end will refer to the original version
+          echo "PACKAGE_VERSION=$(echo "${ARTIFACT_TAG#v}" | sed 's/-/_/g')-1" >> "$GITHUB_ENV"
+      - name: Install package
+        env:
+          RELEASE_CHANNEL: ${{ inputs.release-channel }}
+          VERSION_CHANNEL: ${{ needs.deploy.outputs.component-version-channel }}
+          PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
+        run: |
+          # Install teleport based off of instructions from https://goteleport.com/docs/installation/#linux
+          # This is designed to be changed as little as possible from the source
+          source /etc/os-release
+          VERSION_ID=$(echo $VERSION_ID | cut -d'.' -f1)
+
+          # This is required on container images specifically
+          GPG_KEY_PATH="/tmp/teleport.gpg"
+          openssl s_client -quiet -connect "$ZYPPER_REPO_DOMAIN_NAME:443" -servername "$ZYPPER_REPO_DOMAIN_NAME" <<EOF 2>/dev/null | sed '1,/^\r$/d' > "$GPG_KEY_PATH"
+          GET /gpg HTTP/1.0
+          Host: ${ZYPPER_REPO_DOMAIN_NAME}
+
+          EOF
+          rpm --import "$GPG_KEY_PATH"
+          rm "$GPG_KEY_PATH"
+
+          sudo zypper addrepo --refresh --repo $(rpm --eval "https://${ZYPPER_REPO_DOMAIN_NAME}/$ID/$VERSION_ID/Teleport/%{_arch}/$RELEASE_CHANNEL/$VERSION_CHANNEL/teleport.repo")
+
+          sudo zypper install -y "$PACKAGE_TO_TEST=$PACKAGE_VERSION"
+      - name: Log Teleport version
+        run: teleport version
+      - name: Log package cache information
+        env:
+          PACKAGE_TO_TEST: ${{ inputs.package-to-test }}
+        run: |
+          zypper search -s "$PACKAGE_TO_TEST"
       - name: Verify installed Teleport version matches provided artifact version
         env:
           ARTIFACT_TAG: ${{ inputs.artifact-tag }}
