Run govulncheck against all supported branches (#4320)
* Run govulncheck against all supported branches

* check against origin instead of local

* Add actions:read perm to pull job URL

* Added another GOOS override for v13 windows installer path

* quote directory path in log string

* Clean up failure report

* stop writing to stderr and log err/summary instead

* Change log URL to run attempt HTML url

* cleanup

* Suppress invalid error annotations

* change stop marker

* fix API url

* remove useless markers

Source-commit: gravitational/teleport.e@71913a8baeee2c73f61fb7cf72d6752951ea7fc4
Source-pull-requests: gravitational/teleport.e#4320

diff --git a/e/.github/workflows/nightly-govulncheck.yaml b/e/.github/workflows/nightly-govulncheck.yaml
--- a/e/.github/workflows/nightly-govulncheck.yaml
+++ b/e/.github/workflows/nightly-govulncheck.yaml
@@ -18,30 +18,61 @@ on:
       - .github/workflows/nightly-govulncheck.yaml
 
 jobs:
+  setup:
+    runs-on: ubuntu-latest
+    outputs:
+      branches-json: ${{ steps.branches.outputs.branches-json }}
+    steps:
+      - name: Get the latest release version
+        uses: gravitational/teleport.e/.github/actions/latest-version@master
+        id: latest-version
+      - name: Parse the latest version
+        id: version
+        uses: gravitational/teleport.e/.github/actions/parse-version@master
+        with:
+          version: ${{ steps.latest-version.outputs.latest-version }}
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Get all branches
+          sparse-checkout: non-existant-directory # Don't actually pull files in, only history
+      - name: Get a list of branches to run against
+        id: branches
+        env:
+          LATEST_RELEASE_VERSION: ${{ steps.version.outputs.major }}
+        run: |
+          MAJOR_VERSIONS_TO_CHECK=(
+            "${LATEST_RELEASE_VERSION}"
+            "$(( LATEST_RELEASE_VERSION - 1 ))"
+            "$(( LATEST_RELEASE_VERSION - 2 ))"
+          )
+
+          # Check if a new branch has been cut, but not released yet
+          NEXT_MAJOR_VERSION="$(( LATEST_RELEASE_VERSION + 1 ))"
+          if git rev-parse --verify "origin/branch/v${NEXT_MAJOR_VERSION}" 2>&1 > /dev/null; then
+            echo "Found unreleased version ${NEXT_MAJOR_VERSION}"
+            MAJOR_VERSIONS_TO_CHECK+=("${NEXT_MAJOR_VERSION}")
+          fi
+
+          BRANCHES_TO_CHECK=("master")
+          BRANCHES_TO_CHECK+=("${MAJOR_VERSIONS_TO_CHECK[@]/#/'branch/v'}")
+
+          BRANCHES_JSON="$(jq -cn '$ARGS.positional' --args -- "${BRANCHES_TO_CHECK[@]}")"
+          echo "branches-json=${BRANCHES_JSON}" | tee -a "${GITHUB_OUTPUT}"
+
   run:
     runs-on: ubuntu-22.04-32core
-    env:
-      REPORT_PATH: /tmp/report.txt
+    needs: setup
+    strategy:
+      fail-fast: false
+      matrix:
+        branch: ${{ fromJson(needs.setup.outputs.branches-json) }}
     steps:
       - name: Checkout Teleport
         uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
         with:
-          oss-teleport-ref: master
+          oss-teleport-ref: ${{ matrix.branch }}
           edition: enterprise
-
-      - name: Set slack channel
-        id: slack-config
-        env:
-          DISPATCH_CHANNEL_ID: ${{ inputs.slack-channel-id }}
-          PULL_REQUEST_CHANNEL_ID: C05BHLD737B # #testing-noise channel
-          SCHEDULE_CHANNEL_ID: C0DF0TPMY # #dev-teleport channel
-        run: |
-          case "${GITHUB_EVENT_NAME}" in
-          workflow_dispatch) echo "channel-id=${DISPATCH_CHANNEL_ID}" ;;
-          pull_request) echo "channel-id=${PULL_REQUEST_CHANNEL_ID}" ;;
-          schedule) echo "channel-id=${SCHEDULE_CHANNEL_ID}" ;;
-          *) echo "Unsupported event ${GITHUB_EVENT_NAME}"; exit 1 ;;
-          esac | tee -a "$GITHUB_OUTPUT"
 
       - name: Install Go
         uses: actions/setup-go@v5
@@ -55,7 +86,7 @@ jobs:
 
       - name: Run govulncheck on all Go modules
         env:
-          CURRENT_REPORT_PATH: /tmp/current_report
+          BRANCH: ${{ matrix.branch }}
         run: |
           set -o pipefail
           readarray -d '' MODULE_DIRECTORY_PATHS < \
@@ -63,6 +94,7 @@ jobs:
 
           declare -A MOD_GOOS=(
             [./e/windowsauth/installer]=windows
+            [./e/windowsauth]=windows
           )
           DEFAULT_GOOS=$(go env GOOS)
           
@@ -70,26 +102,19 @@ jobs:
           for MODULE_DIRECTORY_PATH in "${MODULE_DIRECTORY_PATHS[@]}"; do
             MODULE_NAME=$(go list -C "${MODULE_DIRECTORY_PATH}" -m)
             echo "::group::${MODULE_NAME}"
-            echo "Checking ${MODULE_NAME} at ${MODULE_DIRECTORY_PATH}..."
+            echo "Checking ${MODULE_NAME} at '${MODULE_DIRECTORY_PATH}'..."
 
             set +e  # Ignore errors for this part
             GOOS=${MOD_GOOS[${MODULE_DIRECTORY_PATH}]:-${DEFAULT_GOOS}} \
-            govulncheck -C "${MODULE_DIRECTORY_PATH}" -show traces,verbose -test ./... 2>&1 | \
-              tee "${CURRENT_REPORT_PATH}"; \
+            govulncheck -C "${MODULE_DIRECTORY_PATH}" -show traces,verbose -test ./... 2>&1; \
               EXIT_CODE=$?
             set -e
 
             if [[ "${EXIT_CODE}" == 0 ]]; then
               echo "Vuln check passed."
             else
-              echo "Vuln check failed!" >&2
+              echo "::error::Vuln check failed!"
               FAILING_MODULES+=("$MODULE_NAME")
-
-              # Add the module to the job report
-              {
-                echo "Vulnerabilities or symbolic error found in ${MODULE_NAME} at ${MODULE_DIRECTORY_PATH}:"
-                cat "${CURRENT_REPORT_PATH}"
-              } >> "${REPORT_PATH}"
             fi
 
             printf "\n\n::endgroup::\n"
@@ -98,37 +123,50 @@ jobs:
           # Fail if any vulnerabilities were found
           if [[ "${#FAILING_MODULES[@]}" != 0 ]]; then
             {
-              echo "${#FAILING_MODULES[@]} checks failed:"
+              echo
+              echo "${#FAILING_MODULES[@]} modules failed on ${BRANCH}:"
               printf '*  %s\n' "${FAILING_MODULES[@]}"
-            } >&2
+            } | tee -a "${GITHUB_STEP_SUMMARY}"
             exit 1
           fi
 
           echo "All checks passed"
-
+  report:
+    runs-on: ubuntu-latest
+    needs: run
+    if: always()
+    permissions:
+      actions: read
+    steps:
+      - name: Set slack channel
+        id: slack-config
+        env:
+          DISPATCH_CHANNEL_ID: ${{ inputs.slack-channel-id }}
+          PULL_REQUEST_CHANNEL_ID: C05BHLD737B # #testing-noise channel
+          SCHEDULE_CHANNEL_ID: C0DF0TPMY # #dev-teleport channel
+        run: |
+          case "${GITHUB_EVENT_NAME}" in
+          workflow_dispatch) echo "channel-id=${DISPATCH_CHANNEL_ID}" ;;
+          pull_request) echo "channel-id=${PULL_REQUEST_CHANNEL_ID}" ;;
+          schedule) echo "channel-id=${SCHEDULE_CHANNEL_ID}" ;;
+          *) echo "Unsupported event ${GITHUB_EVENT_NAME}"; exit 1 ;;
+          esac | tee -a "$GITHUB_OUTPUT"
       - name: Fetch report data
         id: fetch
-        if: failure()
+        if: needs.run.result != 'success'
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
         run: |
-          {
-            echo "report<<END_OF_REPORT"
-            cat "${REPORT_PATH}"
-            echo END_OF_REPORT
-          } >> "$GITHUB_OUTPUT"
-
           # Fetch link to logs on CI
-          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT}/jobs"
+          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT}"
           curl -fsSL \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${GITHUB_TOKEN}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "${URL}" \
-            | jq -r '"logurl=\(.jobs[0].html_url)"' >> "$GITHUB_OUTPUT"
-
-      - name: Send report to slack
-        if: failure()
+            | jq -r '"logurl=\(.html_url)"' >> "$GITHUB_OUTPUT"
+      - name: Send failure report to slack
+        if: needs.run.result != 'success'
         uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
         env:
           SLACK_BOT_TOKEN: ${{ secrets.TOOLING_ALERTS_SLACK_TOKEN }}
@@ -145,18 +183,14 @@ jobs:
               "attachments": [
                 {
                   "color": "danger",
-                  "title": "Go vulnerabilities detected",
+                  "title": "Go vulnerabilities detected - click here to investigate",
                   "title_link": "${{steps.fetch.outputs.logurl}}"
-                },
-                {
-                  "color": "danger",
-                  "text": ${{ toJSON(steps.fetch.outputs.report) }}
                 }
               ]
             }
 
       - name: Send success report to slack
-        if: success()
+        if: needs.run.result == 'success'
         uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
         env:
           SLACK_BOT_TOKEN: ${{ secrets.TOOLING_ALERTS_SLACK_TOKEN }}
