Adding a tag/version mismatch check to tag-build workflow (#4639)
* Adding a tag/version mismatch check to tag-build workflow

* Fixing a typo

* Adding error message and fixing teleport-version usage

* Testing push

* Fixing a typo

* Removing test workflow

* Fixing linting hopefully

* Removing unecessary input

Source-commit: gravitational/teleport.e@fb4a1d1867fff3f027dafeff1819dd7b347d36db
Source-pull-requests: gravitational/teleport.e#4639

diff --git a/e/.github/workflows/tag-build.yaml b/e/.github/workflows/tag-build.yaml
--- a/e/.github/workflows/tag-build.yaml
+++ b/e/.github/workflows/tag-build.yaml
@@ -85,6 +85,27 @@ jobs:
         run: |
           # Do nothing
 
+      - name: Checkout Teleport
+        uses: gravitational/teleport.e/.github/actions/checkout-teleport@master
+        if: inputs.teleport-version == ''
+        with:
+          oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
+          oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
+          edition: "oss"
+          repo-access-app-id: ${{ secrets.DEPLOY_APP_ID }}
+          repo-access-app-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
+  
+      - name: Reject Tag/Version Mismatch
+        env:
+          TAG: ${{ inputs.oss-teleport-ref }}
+        if: inputs.teleport-version == ''
+        run: |
+          MAKE_VERSION=$(make print-version)
+          if [[ "$TAG" != "v$MAKE_VERSION" ]]; then
+            echo "::error title=Version Mismatch::Tag '$TAG' does not match version in Makefile '$MAKE_VERSION'" >&2
+            exit 1
+          fi
+
   build-linux:
     needs: setup
     strategy:
