Finalize staging env work (#4122)
* Set default environments to staging on all build and publish workflows

* Explicitly reject prereleases sent to production environments

* Set `environment` for AMI publishing

* Don't fail on -cloud prereleases

Source-commit: gravitational/teleport.e@0f5e82238cb8a3f717cddb186004f48998e94fb7
Source-pull-requests: gravitational/teleport.e#4122

diff --git a/e/.github/workflows/tag-build.yaml b/e/.github/workflows/tag-build.yaml
--- a/e/.github/workflows/tag-build.yaml
+++ b/e/.github/workflows/tag-build.yaml
@@ -31,7 +31,7 @@ on:
           GitHub Actions environment in which to run the build. Can be either
           `build-stage` or `build-prod`.
         type: string
-        default: build-prod
+        default: build-stage
 
       cloud-only:
         description: Perform a cloud-only release (distroless OCI only)
@@ -54,6 +54,14 @@ jobs:
         with:
           ref: ${{ inputs.oss-teleport-ref }}
           version: ${{ inputs.teleport-version }}
+      - name: Reject non-cloud prereleases being sent to production
+        if: ${{ contains(inputs.environment, 'prod') && !contains(fromJson('["", "cloud"]'), steps.determine-version.outputs.pre-release) }}
+        env:
+          VERSION: ${{ steps.determine-version.outputs.full }}
+          GH_ENVIRONMENT: ${{ inputs.environment }}
+        run: |
+          echo "::error title=Prerelease sent to production environment::Prereleases ($VERSION) must not be sent to production environments ($GH_ENVIRONMENT)." >&2
+          exit 1
 
       - name: ${{ inputs.workflow-tag }}
         if: inputs.workflow-tag != ''
diff --git a/e/.github/workflows/tag-publish.yaml b/e/.github/workflows/tag-publish.yaml
--- a/e/.github/workflows/tag-publish.yaml
+++ b/e/.github/workflows/tag-publish.yaml
@@ -28,7 +28,7 @@ on:
       environment:
         description: GitHub environment to publish to.
         type: environment
-        default: publish-prod
+        default: publish-stage
 
 jobs:
   setup:
@@ -43,6 +43,14 @@ jobs:
         with:
           ref: ${{ inputs.oss-teleport-ref }}
           version: ${{ inputs.teleport-version }}
+      - name: Reject non-cloud prereleases being sent to production
+        if: ${{ contains(inputs.environment, 'prod') && !contains(fromJson('["", "cloud"]'), steps.determine-version.outputs.pre-release) }}
+        env:
+          VERSION: ${{ steps.determine-version.outputs.full }}
+          GH_ENVIRONMENT: ${{ inputs.environment }}
+        run: |
+          echo "::error title=Prerelease sent to production environment::Prereleases ($VERSION) must not be sent to production environments ($GH_ENVIRONMENT)." >&2
+          exit 1
 
   publish-distroless-oci:
     name: Publish distroless OCI images
@@ -82,6 +90,7 @@ jobs:
       oss-teleport-repo: ${{ inputs.oss-teleport-repo }}
       oss-teleport-ref: ${{ inputs.oss-teleport-ref }}
       release-source-tag: ${{ needs.setup.outputs.version }}
+      environment: ${{ inputs.environment }}
 
   publish-helm:
     name: Publish helm charts
