Run ARM push builds using Kubernetes

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -892,15 +892,13 @@ steps:
 
 ---
 kind: pipeline
-type: exec
-name: push-build-arm
+type: kubernetes
+name: push-build-linux-arm
 
-concurrency:
-  limit: 1
-
-platform:
-  os: linux
-  arch: arm
+environment:
+  RUNTIME: go1.15.5
+  UID: 1000
+  GID: 1000
 
 trigger:
   event:
@@ -917,94 +915,88 @@ trigger:
       - gravitational/*
 
 workspace:
-  path: /dev/shm/push-build-arm
-
-# use ramfs for go build cache - saves wear and tear on the SD card, plus it's faster
-# note: declaring the WORKSPACE_DIR variable once in this block and then trying to
-# quote it in commands below doesn't seem to work; it has to be redeclared as part of
-# the environment inside every individual step. per-pipeline environments seem to be
-# inconsistently implemented across different drone runners and may well be deprecated
-environment:
-  TMPDIR: /dev/shm/push-build-arm/tmp
+  path: /go
 
 clone:
   disable: true
 
 steps:
-  - name: Clean up exec runner storage (pre)
-    environment:
-      WORKSPACE_DIR: /dev/shm/push-build-arm/tmp
-    commands:
-      - set -u
-      - mkdir -p $WORKSPACE_DIR
-      - chmod -R u+rw $WORKSPACE_DIR
-      - rm -rf $WORKSPACE_DIR/go $WORKSPACE_DIR/.ssh
-
   - name: Check out code
+    image: docker:git
     environment:
       GITHUB_PRIVATE_KEY:
         from_secret: GITHUB_PRIVATE_KEY
-      WORKSPACE_DIR: /dev/shm/push-build-arm/tmp
     commands:
-      - set -u
-      - mkdir -p $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - git clone https://github.com/gravitational/teleport.git .
-      - git checkout ${DRONE_TAG:-$DRONE_COMMIT}
-      # fetch enterprise submodules
-      - mkdir -m 0700 $WORKSPACE_DIR/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > $WORKSPACE_DIR/.ssh/id_rsa && chmod 600 $WORKSPACE_DIR/.ssh/id_rsa
-      - ssh-keyscan -H github.com > $WORKSPACE_DIR/.ssh/known_hosts 2>/dev/null
-      - chmod 600 $WORKSPACE_DIR/.ssh/known_hosts
-      - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init e
+      - mkdir -p /go/src/github.com/gravitational/teleport /go/cache
+      - cd /go/src/github.com/gravitational/teleport
+      - git init && git remote add origin ${DRONE_REMOTE_URL}
+      - git fetch origin
+      - git checkout -qf ${DRONE_COMMIT_SHA}
       # this is allowed to fail because pre-4.3 Teleport versions don't use the webassets submodule
-      - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init --recursive webassets || true
-      - rm -rf $WORKSPACE_DIR/.ssh
-      - mkdir -p $WORKSPACE_DIR/go/cache
+      - git submodule update --init webassets || true
+      - mkdir -m 0700 /root/.ssh && echo "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
+      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
+      - git submodule update --init e
+      # do a recursive submodule checkout to get both webassets and webassets/e
+      # this is allowed to fail because pre-4.3 Teleport versions don't use the webassets submodule
+      - git submodule update --init --recursive webassets || true
+      - rm -f /root/.ssh/id_rsa
 
-  - name: Build ARM artifacts
+  - name: Build artifacts
+    image: docker
     environment:
-      GOPATH: /dev/shm/push-build-arm/tmp/go
-      GOCACHE: /dev/shm/push-build-arm/tmp/go/cache
+      UID: 1000
+      GID: 1000
+      GOPATH: /go
       OS: linux
       ARCH: arm
-      WORKSPACE_DIR: /dev/shm/push-build-arm/tmp
+    volumes:
+      - name: dockersock
+        path: /var/run
     commands:
-      - set -u
-      - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - make clean release OS=$OS ARCH=$ARCH
+      - apk add --no-cache make
+      - chown -R $UID:$GID /go
+      - docker pull quay.io/gravitational/teleport-buildbox-arm:$RUNTIME || true
+      - cd /go/src/github.com/gravitational/teleport
+      - make -C build.assets release-arm
 
-  - name: Clean up exec runner storage (post)
-    environment:
-      WORKSPACE_DIR: /dev/shm/push-build-arm/tmp
-    commands:
-      - set -u
-      - chmod -R u+rw $WORKSPACE_DIR
-      - rm -rf $WORKSPACE_DIR/go $WORKSPACE_DIR/.ssh
-
-  - name: Send Slack notification (exec)
-    environment:
-      SLACK_WEBHOOK:
+  - name: Send Slack notification
+    image: plugins/slack
+    settings:
+      webhook:
         from_secret: SLACK_WEBHOOK_DEV_TELEPORT
-    commands:
-      - |
-        export DRONE_BUILD_LINK="${DRONE_SYSTEM_PROTO}://${DRONE_SYSTEM_HOSTNAME}/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}"
-        export GOOS=$(go env GOOS)
-        export GOARCH=$(go env GOARCH)
-        curl -sL -X POST -H 'Content-type: application/json' --data "{\"text\":\"Warning: \`$GOOS-$GOARCH\` artifact build failed - please investigate immediately!\nBranch: \`${DRONE_BRANCH}\`\nCommit: \`${DRONE_COMMIT_SHA}\`\nLink: $DRONE_BUILD_LINK\"}" $SLACK_WEBHOOK
+      channel: dev-teleport
+      template: |
+        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
+        `linux-arm` artifact build failed.
+        *Warning:* This is a genuine failure to build the Teleport binary from `{{ build.branch }}` (likely due to a bad merge or commit) and should be investigated immediately.
+        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
+        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
+        Author: <https://github.com/{{ build.author }}|{{ build.author }}>
+        <{{ build.link }}|Visit Drone build page ↗>
     when:
       status: [failure]
+
+services:
+  - name: Start Docker
+    image: docker:dind
+    volumes:
+      - name: dockersock
+        path: /var/run
+
+volumes:
+  - name: dockersock
+    temp: {}
 
 ---
 kind: pipeline
-type: exec
-name: push-build-arm64
+type: kubernetes
+name: push-build-linux-arm64
 
-concurrency:
-  limit: 1
-
-platform:
-  os: linux
-  arch: arm64
+environment:
+  RUNTIME: go1.15.5
+  UID: 1000
+  GID: 1000
 
 trigger:
   event:
@@ -1021,82 +1013,78 @@ trigger:
       - gravitational/*
 
 workspace:
-  path: /dev/shm/push-build-arm64
-
-# use ramfs for go build cache
-# note: declaring the WORKSPACE_DIR variable once in this block and then trying to
-# quote it in commands below doesn't seem to work; it has to be redeclared as part of
-# the environment inside every individual step. per-pipeline environments seem to be
-# inconsistently implemented across different drone runners and may well be deprecated
-environment:
-  TMPDIR: /dev/shm/push-build-arm64/tmp
+  path: /go
 
 clone:
   disable: true
 
 steps:
-  - name: Clean up exec runner storage (pre)
-    environment:
-      WORKSPACE_DIR: /dev/shm/push-build-arm64/tmp
-    commands:
-      - set -u
-      - mkdir -p $WORKSPACE_DIR
-      - chmod -R u+rw $WORKSPACE_DIR
-      - rm -rf $WORKSPACE_DIR/go $WORKSPACE_DIR/.ssh
-
   - name: Check out code
+    image: docker:git
     environment:
       GITHUB_PRIVATE_KEY:
         from_secret: GITHUB_PRIVATE_KEY
-      WORKSPACE_DIR: /dev/shm/push-build-arm64/tmp
     commands:
-      - set -u
-      - mkdir -p $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - git clone https://github.com/gravitational/teleport.git .
-      - git checkout ${DRONE_TAG:-$DRONE_COMMIT}
-      # fetch enterprise submodules
-      - mkdir -m 0700 $WORKSPACE_DIR/.ssh && echo -n "$GITHUB_PRIVATE_KEY" > $WORKSPACE_DIR/.ssh/id_rsa && chmod 600 $WORKSPACE_DIR/.ssh/id_rsa
-      - ssh-keyscan -H github.com > $WORKSPACE_DIR/.ssh/known_hosts 2>/dev/null
-      - chmod 600 $WORKSPACE_DIR/.ssh/known_hosts
-      - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init e
+      - mkdir -p /go/src/github.com/gravitational/teleport /go/cache
+      - cd /go/src/github.com/gravitational/teleport
+      - git init && git remote add origin ${DRONE_REMOTE_URL}
+      - git fetch origin
+      - git checkout -qf ${DRONE_COMMIT_SHA}
       # this is allowed to fail because pre-4.3 Teleport versions don't use the webassets submodule
-      - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init --recursive webassets || true
-      - rm -rf $WORKSPACE_DIR/.ssh
-      - mkdir -p $WORKSPACE_DIR/go/cache
+      - git submodule update --init webassets || true
+      - mkdir -m 0700 /root/.ssh && echo "$GITHUB_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
+      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
+      - git submodule update --init e
+      # do a recursive submodule checkout to get both webassets and webassets/e
+      # this is allowed to fail because pre-4.3 Teleport versions don't use the webassets submodule
+      - git submodule update --init --recursive webassets || true
+      - rm -f /root/.ssh/id_rsa
 
-  - name: Build ARM64 artifacts
+  - name: Build artifacts
+    image: docker
     environment:
-      GOPATH: /dev/shm/push-build-arm64/tmp/go
-      GOCACHE: /dev/shm/push-build-arm64/tmp/go/cache
+      UID: 1000
+      GID: 1000
+      GOPATH: /go
       OS: linux
       ARCH: arm64
-      WORKSPACE_DIR: /dev/shm/push-build-arm64/tmp
+    volumes:
+      - name: dockersock
+        path: /var/run
     commands:
-      - set -u
-      - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - make clean release OS=$OS ARCH=$ARCH
+      - apk add --no-cache make
+      - chown -R $UID:$GID /go
+      - docker pull quay.io/gravitational/teleport-buildbox-arm64:$RUNTIME || true
+      - cd /go/src/github.com/gravitational/teleport
+      - make -C build.assets release-arm64
 
-  - name: Clean up exec runner storage (post)
-    environment:
-      WORKSPACE_DIR: /dev/shm/push-build-arm64/tmp
-    commands:
-      - set -u
-      - chmod -R u+rw $WORKSPACE_DIR
-      - rm -rf $WORKSPACE_DIR/go $WORKSPACE_DIR/.ssh
-
-  - name: Send Slack notification (exec)
-    environment:
-      SLACK_WEBHOOK:
+  - name: Send Slack notification
+    image: plugins/slack
+    settings:
+      webhook:
         from_secret: SLACK_WEBHOOK_DEV_TELEPORT
-    commands:
-      - |
-        export DRONE_BUILD_LINK="${DRONE_SYSTEM_PROTO}://${DRONE_SYSTEM_HOSTNAME}/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}"
-        export GOOS=$(go env GOOS)
-        export GOARCH=$(go env GOARCH)
-        curl -sL -X POST -H 'Content-type: application/json' --data "{\"text\":\"Warning: \`$GOOS-$GOARCH\` artifact build failed - please investigate immediately!\nBranch: \`${DRONE_BRANCH}\`\nCommit: \`${DRONE_COMMIT_SHA}\`\nLink: $DRONE_BUILD_LINK\"}" $SLACK_WEBHOOK
+      channel: dev-teleport
+      template: |
+        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
+        `linux-arm64` artifact build failed.
+        *Warning:* This is a genuine failure to build the Teleport binary from `{{ build.branch }}` (likely due to a bad merge or commit) and should be investigated immediately.
+        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
+        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
+        Author: <https://github.com/{{ build.author }}|{{ build.author }}>
+        <{{ build.link }}|Visit Drone build page ↗>
     when:
       status: [failure]
+
+services:
+  - name: Start Docker
+    image: docker:dind
+    volumes:
+      - name: dockersock
+        path: /var/run
+
+volumes:
+  - name: dockersock
+    temp: {}
 
 ---
 kind: pipeline
@@ -4086,6 +4074,6 @@ volumes:
 
 ---
 kind: signature
-hmac: fba528ba4b524017a1d7ab8ffd1fad9adb80e96302490334f623d125de81f6c7
+hmac: b50ac547583f279cc1bba00c9d086cc5d231c179718616d3ace7481dc192ef45
 
 ...
