Fix .drone.yml.

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -4593,28 +4593,28 @@ steps:
       target: /
       strip_prefix: /go/chart
 
-  # NOTE: all mandatory steps for a release promotion need to go BEFORE this
-  # step, as there is a chance that everything afterwards will be skipped.
-  #
-  # this step exits early and skips all remanining steps in the pipeline if the
-  # tag looks like a pre-release, to avoid publishing RPMs for pre-release builds.
-  - name: Determine whether RPM/DEB packages should be published to repos
-    image: docker
-    commands:
-      - |
-        if [ "${DRONE_REPO}" != "gravitational/teleport" ]; then
-          echo "---> Not publishing ${DRONE_REPO} packages to repos"
-          exit 78
-        fi
-        # length will be 0 after filtering if this is a pre-release, >0 otherwise
-        FILTERED_TAG_LENGTH=$(echo ${DRONE_TAG} | egrep -v '(alpha|beta|dev|rc)' | wc -c)
-        if [ $$FILTERED_TAG_LENGTH -eq 0 ]; then
-          echo "---> ${DRONE_TAG} looks like a pre-release, not publishing packages to repos"
-          # exit pipeline early with success status
-          exit 78
-        else
-          echo "---> Publishing packages to repos for ${DRONE_TAG}"
-        fi
+  ## NOTE: all mandatory steps for a release promotion need to go BEFORE this
+  ## step, as there is a chance that everything afterwards will be skipped.
+  ##
+  ## this step exits early and skips all remanining steps in the pipeline if the
+  ## tag looks like a pre-release, to avoid publishing RPMs for pre-release builds.
+  #- name: Determine whether RPM/DEB packages should be published to repos
+  #  image: docker
+  #  commands:
+  #    - |
+  #      if [ "${DRONE_REPO}" != "gravitational/teleport" ]; then
+  #        echo "---> Not publishing ${DRONE_REPO} packages to repos"
+  #        exit 78
+  #      fi
+  #      # length will be 0 after filtering if this is a pre-release, >0 otherwise
+  #      FILTERED_TAG_LENGTH=$(echo ${DRONE_TAG} | egrep -v '(alpha|beta|dev|rc)' | wc -c)
+  #      if [ $$FILTERED_TAG_LENGTH -eq 0 ]; then
+  #        echo "---> ${DRONE_TAG} looks like a pre-release, not publishing packages to repos"
+  #        # exit pipeline early with success status
+  #        exit 78
+  #      else
+  #        echo "---> Publishing packages to repos for ${DRONE_TAG}"
+  #      fi
 
   - name: "RPM: Download RPM repository"
     image: amazon/aws-cli
@@ -4644,116 +4644,118 @@ steps:
     - cp -a /go/artifacts/*arm.rpm /rpmrepo/teleport/${DRONE_TAG##v}/
     - cp -a /go/artifacts/*arm64.rpm /rpmrepo/teleport/${DRONE_TAG##v}/
     - cp -a /go/artifacts/*i386.rpm /rpmrepo/teleport/${DRONE_TAG##v}/
+    - ls -lah /go/artifacts/
+    - ls -lah /rpmrepo/teleport/${DRONE_TAG##v}/
 
-  # we do this using a CentOS 7 container to make sure that the repo files are
-  # compatible with older versions, also there's no createrepo package in alpine main
-  - name: "RPM: Regenerate RPM repository metadata"
-    image: centos:7
-    volumes:
-      - name: rpmrepo
-        path: /rpmrepo
-    commands:
-    - yum -y install createrepo
-    - createrepo --cachedir /rpmrepo/teleport/cache --update /rpmrepo/teleport
+  ## we do this using a CentOS 7 container to make sure that the repo files are
+  ## compatible with older versions, also there's no createrepo package in alpine main
+  #- name: "RPM: Regenerate RPM repository metadata"
+  #  image: centos:7
+  #  volumes:
+  #    - name: rpmrepo
+  #      path: /rpmrepo
+  #  commands:
+  #  - yum -y install createrepo
+  #  - createrepo --cachedir /rpmrepo/teleport/cache --update /rpmrepo/teleport
 
-  - name: "RPM: Publish RPM repository to S3"
-    image: amazon/aws-cli
-    environment:
-      AWS_S3_BUCKET:
-        from_secret: RPMREPO_AWS_S3_BUCKET
-      AWS_ACCESS_KEY_ID:
-        from_secret: RPMREPO_AWS_ACCESS_KEY_ID
-      AWS_SECRET_ACCESS_KEY:
-        from_secret: RPMREPO_AWS_SECRET_ACCESS_KEY
-    volumes:
-      - name: rpmrepo
-        path: /rpmrepo
-    commands:
-    - aws s3 sync /rpmrepo/teleport/ s3://$AWS_S3_BUCKET/teleport/
+  #- name: "RPM: Publish RPM repository to S3"
+  #  image: amazon/aws-cli
+  #  environment:
+  #    AWS_S3_BUCKET:
+  #      from_secret: RPMREPO_AWS_S3_BUCKET
+  #    AWS_ACCESS_KEY_ID:
+  #      from_secret: RPMREPO_AWS_ACCESS_KEY_ID
+  #    AWS_SECRET_ACCESS_KEY:
+  #      from_secret: RPMREPO_AWS_SECRET_ACCESS_KEY
+  #  volumes:
+  #    - name: rpmrepo
+  #      path: /rpmrepo
+  #  commands:
+  #  - aws s3 sync /rpmrepo/teleport/ s3://$AWS_S3_BUCKET/teleport/
 
-  - name: Download DEB repo contents
-    image: amazon/aws-cli
-    environment:
-      AWS_S3_BUCKET:
-        from_secret: DEBREPO_AWS_S3_BUCKET
-      AWS_ACCESS_KEY_ID:
-        from_secret: DEBREPO_AWS_ACCESS_KEY_ID
-      AWS_SECRET_ACCESS_KEY:
-        from_secret: DEBREPO_AWS_SECRET_ACCESS_KEY
-    volumes:
-      - name: debrepo
-        path: /debrepo
-    commands:
-    # we explicitly want to delete anything present locally which has been deleted
-    # from the upstream S3 bucket
-    - mkdir -p /debrepo/teleport
-    - aws s3 sync s3://$AWS_S3_BUCKET/teleport /debrepo/teleport --delete
+  #- name: Download DEB repo contents
+  #  image: amazon/aws-cli
+  #  environment:
+  #    AWS_S3_BUCKET:
+  #      from_secret: DEBREPO_AWS_S3_BUCKET
+  #    AWS_ACCESS_KEY_ID:
+  #      from_secret: DEBREPO_AWS_ACCESS_KEY_ID
+  #    AWS_SECRET_ACCESS_KEY:
+  #      from_secret: DEBREPO_AWS_SECRET_ACCESS_KEY
+  #  volumes:
+  #    - name: debrepo
+  #      path: /debrepo
+  #  commands:
+  #  # we explicitly want to delete anything present locally which has been deleted
+  #  # from the upstream S3 bucket
+  #  - mkdir -p /debrepo/teleport
+  #  - aws s3 sync s3://$AWS_S3_BUCKET/teleport /debrepo/teleport --delete
 
-  - name: Build DEB repo
-    image: ubuntu:20.04
-    environment:
-      DEBIAN_FRONTEND: noninteractive
-      GNUPGHOME: /tmpfs/gnupg
-      GPG_RPM_SIGNING_ARCHIVE:
-        from_secret: GPG_RPM_SIGNING_ARCHIVE
-    volumes:
-      - name: dockersock
-        path: /var/run
-      - name: debrepo
-        path: /debrepo
-      # for in-memory tmpfs for key material
-      - name: tmpfs
-        path: /tmpfs
-    commands:
-      - |
-        # install needed tools
-        apt-get -y update && apt-get -y install curl gzip gnupg2 reprepro tar
-      - |
-        # write config files
-        mkdir -p /go/reprepro/teleport/conf /go/reprepro/teleport/public
-        cat << EOF > /go/reprepro/teleport/conf/distributions
-        Origin: teleport
-        Label: teleport
-        Codename: stable
-        Architectures: i386 amd64 arm arm64
-        Components: main
-        Description: apt repository for teleport
-        SignWith: 6282C411
-        EOF
-        cat << EOF > /go/reprepro/teleport/conf/options
-        verbose
-        basedir /go/reprepro/teleport
-        EOF
-      - |
-        # extract signing key
-        mkdir -m0700 $GNUPGHOME
-        echo "$GPG_RPM_SIGNING_ARCHIVE" | base64 -d | tar -xzf - -C $GNUPGHOME
-        chown -R root:root $GNUPGHOME
-      - |
-        # create repo
-        cd /go/reprepro/teleport
-        reprepro --outdir /go/reprepro/teleport/public includedeb stable /go/artifacts/teleport*.deb
-      - |
-        # clean up gnupg
-        rm -rf $GNUPGHOME
-      - |
-        # copy artifacts to PVC
-        cp -r /go/reprepro/teleport /debrepo/
+  #- name: Build DEB repo
+  #  image: ubuntu:20.04
+  #  environment:
+  #    DEBIAN_FRONTEND: noninteractive
+  #    GNUPGHOME: /tmpfs/gnupg
+  #    GPG_RPM_SIGNING_ARCHIVE:
+  #      from_secret: GPG_RPM_SIGNING_ARCHIVE
+  #  volumes:
+  #    - name: dockersock
+  #      path: /var/run
+  #    - name: debrepo
+  #      path: /debrepo
+  #    # for in-memory tmpfs for key material
+  #    - name: tmpfs
+  #      path: /tmpfs
+  #  commands:
+  #    - |
+  #      # install needed tools
+  #      apt-get -y update && apt-get -y install curl gzip gnupg2 reprepro tar
+  #    - |
+  #      # write config files
+  #      mkdir -p /go/reprepro/teleport/conf /go/reprepro/teleport/public
+  #      cat << EOF > /go/reprepro/teleport/conf/distributions
+  #      Origin: teleport
+  #      Label: teleport
+  #      Codename: stable
+  #      Architectures: i386 amd64 arm arm64
+  #      Components: main
+  #      Description: apt repository for teleport
+  #      SignWith: 6282C411
+  #      EOF
+  #      cat << EOF > /go/reprepro/teleport/conf/options
+  #      verbose
+  #      basedir /go/reprepro/teleport
+  #      EOF
+  #    - |
+  #      # extract signing key
+  #      mkdir -m0700 $GNUPGHOME
+  #      echo "$GPG_RPM_SIGNING_ARCHIVE" | base64 -d | tar -xzf - -C $GNUPGHOME
+  #      chown -R root:root $GNUPGHOME
+  #    - |
+  #      # create repo
+  #      cd /go/reprepro/teleport
+  #      reprepro --outdir /go/reprepro/teleport/public includedeb stable /go/artifacts/teleport*.deb
+  #    - |
+  #      # clean up gnupg
+  #      rm -rf $GNUPGHOME
+  #    - |
+  #      # copy artifacts to PVC
+  #      cp -r /go/reprepro/teleport /debrepo/
 
-  - name: Sync DEB repo changes to S3
-    image: amazon/aws-cli
-    environment:
-      AWS_S3_BUCKET:
-        from_secret: DEBREPO_AWS_S3_BUCKET
-      AWS_ACCESS_KEY_ID:
-        from_secret: DEBREPO_AWS_ACCESS_KEY_ID
-      AWS_SECRET_ACCESS_KEY:
-        from_secret: DEBREPO_AWS_SECRET_ACCESS_KEY
-    volumes:
-      - name: debrepo
-        path: /debrepo
-    commands:
-    - aws s3 sync /debrepo/teleport/ s3://$AWS_S3_BUCKET/teleport/
+  #- name: Sync DEB repo changes to S3
+  #  image: amazon/aws-cli
+  #  environment:
+  #    AWS_S3_BUCKET:
+  #      from_secret: DEBREPO_AWS_S3_BUCKET
+  #    AWS_ACCESS_KEY_ID:
+  #      from_secret: DEBREPO_AWS_ACCESS_KEY_ID
+  #    AWS_SECRET_ACCESS_KEY:
+  #      from_secret: DEBREPO_AWS_SECRET_ACCESS_KEY
+  #  volumes:
+  #    - name: debrepo
+  #      path: /debrepo
+  #  commands:
+  #  - aws s3 sync /debrepo/teleport/ s3://$AWS_S3_BUCKET/teleport/
 
 services:
   - name: Start Docker
@@ -4781,6 +4783,6 @@ volumes:
       name: drone-s3-debrepo-pvc
 ---
 kind: signature
-hmac: b3ea3b08231c8687650d3605f624cf5bacfbc8088e8567f43518079383f4adac
+hmac: b74686aefc22e7ea094e6856860dbf11eeea679d77d780824c9854d612a1561f
 
 ...
