field-not-required

diff --git a/integrations/operator/Makefile b/integrations/operator/Makefile
--- a/integrations/operator/Makefile
+++ b/integrations/operator/Makefile
@@ -12,8 +12,17 @@ IMG ?= teleport-operator:latest
 # across all builds.
 include ../../build.assets/versions.mk
 
+# Setting SHELL to bash allows bash commands to be executed by recipes.
+# This is a requirement for 'setup-envtest.sh' in the test target.
+# Options are set to exit when a recipe line exits non-zero or a piped command fails.
+SHELL = /usr/bin/env bash -o pipefail
+.SHELLFLAGS = -ec
+
 # include BUILDBOX_VERSION, BUILDBOX and BUILDBOX_variant variables
 include ../../build.assets/images.mk
+
+# include setup-envtest binary
+include ./envtest.mk
 
 # Configure which compiler and buildbox to use
 OS ?= $(shell go env GOOS)
@@ -65,43 +74,24 @@ help: ## Display this help.
 
 ##@ Development
 
-
 .PHONY: crd ## Single command to generate anything CRD-related (manifests and docs)
-crd: crd-docs crd-manifests
+crd: crdgen crd-docs
 
-.PHONY: generate
-generate: generate-types crd ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
+.PHONY: crdgen
+crdgen: ## Generate CRDs
+	make -C crdgen
 
-generate-types: controller-gen
-	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
-
-crdgenfiles := $(wildcard crdgen/*.go)
-
-.PHONY: crdgen ## Builds both crd and crd documentation protoc plugins.
-crdgen: crdgen/build/protoc-gen-crd crdgen/build/protoc-gen-crd-docs
-
-crdgen/build/%: crdgen/cmd/%/main.go crdgen/cmd/%/debug.go $(crdgenfiles)
-	mkdir -p crdgen/build
-	go build -o $@ github.com/gravitational/teleport/integrations/operator/crdgen/cmd/$*
-
-# List of protos used for CRD generation.
-# If you are adding a new resource, you will want to add your proto file here.
 PROTOS = \
 	teleport/loginrule/v1/loginrule.proto \
 	teleport/accesslist/v1/accesslist.proto \
 	teleport/legacy/types/types.proto \
 	teleport/machineid/v1/bot.proto \
-	teleport/workloadidentity/v1/resource.proto \
-	teleport/autoupdate/v1/autoupdate.proto \
-	teleport/summarizer/v1/summarizer.proto \
-	teleport/accessmonitoringrules/v1/access_monitoring_rules.proto \
-	teleport/scopes/joining/v1/token.proto \
-	teleport/scopes/access/v1/role.proto \
-	teleport/scopes/access/v1/assignment.proto
+	teleport/workloadidentity/v1/resource.proto
 
-.PHONY: crd-manifests
-crd-manifests: crdgen ## Generates CRD manifests using crdgen.
-	@echo "## Generating CRD manifests"
+.PHONY: manifests
+manifests: crdgen controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
+# Generate CRDs for apis/resources (custom generation through protoc plugin).
+
 # The wrappers.proto file needed for this generator exist only inside the go mod cache,
 # so we retrieve the file path for the cached proto files with go mod tools.
 	$(eval PROTOBUF_MOD_PATH := $(shell go mod download --json github.com/gogo/protobuf | awk -F: '/"Dir"/ { print $$2 }' | tr -d ' ",'))
@@ -118,9 +108,13 @@ crd-manifests: crdgen ## Generates CRD manifests using crdgen.
 	rm -r ../../examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/
 	cp -r ./config/crd/bases/ ../../examples/chart/teleport-cluster/charts/teleport-operator/operator-crds
 
+.PHONY: build-docs-plugin
+build-docs-plugin: ## Build the protoc plugin for generating docs
+	make -C crdgen build-docs
+
 .PHONY: crd-docs
-crd-docs: crdgen/build/protoc-gen-crd-docs ## Generate CRD reference docs.
-	@echo "## Generating CRD documentation"
+crd-docs: build-docs-plugin ## Generate CRD reference docs.
+
 # The wrappers.proto file needed for this generator exist only inside the go mod cache,
 # so we retrieve the file path for the cached proto files with go mod tools.
 	$(eval PROTOBUF_MOD_PATH := $(shell go mod download --json github.com/gogo/protobuf | awk -F: '/"Dir"/ { print $$2 }' | tr -d ' ",'))
@@ -130,58 +124,48 @@ crd-docs: crdgen/build/protoc-gen-crd-docs ## Generate CRD reference docs.
 			-I=../../api/proto \
 			-I=$(PROTOBUF_MOD_PATH) \
 			--plugin=./crdgen/build/protoc-gen-crd-docs \
-			--crd-docs_out=../../docs/pages/reference/infrastructure-as-code/operator-resources/ \
+			--crd-docs_out=../../docs/pages/reference/operator-resources/ \
 			"$${proto}"; \
 	done
 
-# crd-manifests-diff renders CRDs using crdgen in a temporary directory, then compares the rendered CRDs
-# with the ones from the config/crd/base directory. Any difference causes a non-zero return code.
-.PHONY: crd-manifests-diff
-crd-manifests-diff: crdgen
-	@echo "## Checking if CRD manifests changed"
-	$(eval PROTOBUF_MOD_PATH := $(shell go mod download --json github.com/gogo/protobuf | awk -F: '/"Dir"/ { print $$2 }' | tr -d ' ",'))
-	$(eval CRD_OUT_PATH := $(shell mktemp -d))
+.PHONY: generate
+generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
+	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
 
-	for proto in $(PROTOS); do \
-		protoc \
-			-I=../../api/proto/ \
-			-I=$(PROTOBUF_MOD_PATH) \
-			--plugin=./crdgen/build/protoc-gen-crd \
-			--crd_out=$(CRD_OUT_PATH) \
-			"$${proto}"; \
-	done
+.PHONY: fmt
+fmt: ## Run go fmt against code.
+	go fmt ./...
 
-	diff -N config/crd/bases $(CRD_OUT_PATH);\
-	EXIT_CODE=$$?;\
-	rm -rf $(CRD_OUT_PATH) $(CUSTOM_IMPORTS_TMP_DIR);\
-	exit $$EXIT_CODE
-
-# This is a helper to dump a request sent to crdgen.
-# See crdgen/DEBUG.md for instruction on how to use this target to replay crdgen with a debugger attached.
-.PHONY: debug-dump-request
-debug-dump-request:
-	$(eval PROTOBUF_MOD_PATH := $(shell go mod download --json github.com/gogo/protobuf | awk -F: '/"Dir"/ { print $$2 }' | tr -d ' ",'))
-	for proto in $(PROTOS); do \
-		protoc \
-			-I=../../api/proto/ \
-			-I=$(PROTOBUF_MOD_PATH) \
-			--plugin=./crdgen/hack/protoc-gen-dump \
-			--dump_out="." \
-			"$${proto}"; \
-	done
+.PHONY: vet
+vet: ## Run go vet against code.
+	go vet ./...
 
 $(TEST_LOG_DIR):
 	mkdir $(TEST_LOG_DIR)
 
 .PHONY: test
-test: generate | $(TEST_LOG_DIR) ## Run tests.
+test: manifests generate fmt vet $(ENVTEST) crdgen-test |  $(TEST_LOG_DIR) ## Run tests.
+test: export KUBEBUILDER_ASSETS=$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)
+test:
 	gotestsum --junitfile $(TEST_LOG_DIR)/unit-tests-operator.xml --jsonfile $(TEST_LOG_DIR)/unit-tests-operator.json
+
+.PHONY: echo-kubebuilder-assets
+echo-kubebuilder-assets:
+	@echo KUBEBUILDER_ASSETS=$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)
+
+.PHONY: crdgen-test
+crdgen-test: ## Run crdgen tests.
+	make -C crdgen test
 
 ##@ Build
 
 .PHONY: build
-build: generate ## Build manager binary.
+build: generate fmt vet ## Build manager binary.
 	go build -trimpath -tags "kustomize_disable_go_plugin_support" -o bin/manager main.go namespace.go config.go
+
+.PHONY: run
+run: manifests generate fmt vet ## Run a controller from your host.
+	go run ./main.go ./namespace.go
 
 .PHONY: docker-build
 docker-build: OS = linux
@@ -208,6 +192,7 @@ $(LOCALBIN):
 CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen
 
 ## Tool Versions
+KUSTOMIZE_VERSION ?= v3.8.7
 CONTROLLER_TOOLS_VERSION ?= v0.20.0
 
 .PHONY: controller-gen
@@ -217,33 +202,12 @@ $(CONTROLLER_GEN): $(LOCALBIN)
 
 # The target below is used to create an operator build, a local test cluster and run it.
 # This uses k3d, if you want to use kind, feel free to contribute an alternative taget.
-# When running from scratch, run k3d cluster create k3s-default to first create your k3d cluster.
-#
-# By default, this uses a released Teleport image.
 # To use it you must set `TELEPORT_VERSION=X.Y.Z`, with "X.Y.Z" being an existing release.
-# To use a locally built Teleport image instead, override TELEPORT_IMAGE and TELEPORT_IMAGE_VERSION:
-#   make k3d-deploy TELEPORT_IMAGE=teleport TELEPORT_IMAGE_VERSION=19.0.0-dev-arm64
-#
-# When TELEPORT_IMAGE is overridden from its default, a local build is assumed:
-# the local image is imported into k3d and TELEPORT_UNSTABLE_SCOPES=true is set.
-#
-# For enterprise builds, also set ENTERPRISE=1:
-#   make k3d-deploy ENTERPRISE=1 TELEPORT_IMAGE=teleport TELEPORT_IMAGE_VERSION=19.0.0-dev-arm64
-#
-# When using a local build, you must:
-#   1. Build the teleport image first (make image from repo root)
-#   2. For enterprise images, create the license secret before deploying:
-#      kubectl -n test create secret generic license --from-file=license.pem=e/fixtures/license-all-features.pem
 K3D_CLUSTER_NAME ?= k3s-default
 GIT_HASH := $(shell git rev-parse --short HEAD)
 GIT_DIRTY := $(shell git diff-index --quiet HEAD -- || echo "dirty")
 TIMESTAMP := $(shell date +%Y%m%d%H%M%S)
-TELEPORT_VERSION ?= 19.0.0-dev
-TELEPORT_IMAGE_DEFAULT := public.ecr.aws/gravitational/teleport-distroless
-TELEPORT_IMAGE ?= $(TELEPORT_IMAGE_DEFAULT)
-TELEPORT_IMAGE_VERSION ?= 18.8.1
-LOCAL_BUILD := $(if $(filter-out $(TELEPORT_IMAGE_DEFAULT),$(TELEPORT_IMAGE)),1,)
-ARCH ?= $(shell go env GOARCH)
+TELEPORT_VERSION?=19.0.0-dev
 
 .PHONY: k3d-deploy
 k3d-deploy: VERSION := $(TELEPORT_VERSION)-$(GIT_HASH)$(if $(GIT_DIRTY),-$(TIMESTAMP))
@@ -255,26 +219,16 @@ k3d-deploy: generate docker-build
 	k3d kubeconfig get $(K3D_CLUSTER_NAME) > "$(KUBECONFIG)"
 	#
 	cat "$(KUBECONFIG)"
-	# Import container images
-ifeq ($(LOCAL_BUILD),1)
-	k3d image import -c $(K3D_CLUSTER_NAME) $(IMG) $(TELEPORT_IMAGE):$(TELEPORT_IMAGE_VERSION)
-else
+	# Import container image
 	k3d image import -c $(K3D_CLUSTER_NAME) $(IMG)
-endif
 	# deploy a teleport cluster with the operator
-	# To add feature flags, append --set "extraEnv[N].name=..." lines below.
 	KUBECONFIG=$(KUBECONFIG) helm upgrade \
 		--install --create-namespace --namespace=test \
 		teleport-cluster ../../examples/chart/teleport-cluster \
 		--set "clusterName=test" \
 		--set "operator.enabled=true" \
-		--set "teleportVersionOverride=$(TELEPORT_IMAGE_VERSION)" \
+		--set "teleportVersionOverride=18.6.4" \
 		--set "operator.teleportVersionOverride=$(VERSION)" \
-		--set "operator.image=$(subst :$(VERSION),,$(IMG))" \
-		--set "extraEnv[0].name=TELEPORT_UNSTABLE_SCOPES" \
-		--set "extraEnv[0].value=yes" \
-		$(if $(LOCAL_BUILD),--set "image=$(TELEPORT_IMAGE)") \
-		$(if $(ENTERPRISE),--set "enterprise=true") \
-		$(if $(ENTERPRISE),--set "enterpriseImage=$(TELEPORT_IMAGE)")
+		--set "operator.image=$(subst :$(VERSION),,$(IMG))"
 
 	rm $$KUBECONFIG
