Remove testing symbols from enterprise binaries  (#7066)
* Remove testing symbols from enterprise binaries

lib/auth/ssotestlib was the last way testing symbols were being
included in builds. FakeOIDC was removed entirely as it was not
referenced. FakeSAML was moved into lib/auth/saml_test.go since
that was the only place referencing it.

* Lint for test symbols

To prevent testing symbols from sneaking back into
production binaries a new lint-test-symbols Make target has
been added, and is called during linting in CI.

This was copied from https://github.com/gravitational/teleport/pull/57905.

Source-commit: gravitational/teleport.e@b8ee5dc9361cea7f24564b0c265b266ba615b2e4
Source-pull-requests: gravitational/teleport.e#7066

diff --git a/e/Makefile b/e/Makefile
--- a/e/Makefile
+++ b/e/Makefile
@@ -512,6 +512,38 @@ ifndef GITTAG
 	$(error GITTAG is not set)
 endif
 
+
+#
+# Install goda to lint testing symbols
+#
+.PHONY: ensure-goda
+ensure-goda:
+# Install goda if it's not already installed
+ ifeq (, $(shell command -v goda))
+	go install github.com/loov/goda@latest
+endif
+
+#
+# Checks that testing symbols and the testify library is not included in binaries.
+# 
+# 
+.PHONY: lint-test-symbols
+lint-test-symbols: ensure-goda
+	@testing_count=`goda tree "reach(github.com/gravitational/teleport/e/tool/...:all, testing)" | tee /dev/stderr | wc -l | tr -d ' '`; \
+	if [ "$$testing_count" -gt 0 ]; then \
+		echo ""; \
+		echo "FAIL: \"testing\" is included in binaries"; \
+	fi; \
+	testify_count=`goda tree "reach(github.com/gravitational/teleport/e/tool/...:all, github.com/stretchr/testify/...)" | tee /dev/stderr | wc -l | tr -d ' '`; \
+	if [ "$$testify_count" -gt 0 ]; then \
+		echo ""; \
+		echo "FAIL: \"github.com/stretchr/testify\" is included in binaries"; \
+	fi; \
+	if [ "$$testing_count" -gt 0 ] || [ "$$testify_count" -gt 0 ]; then \
+		exit 1; \
+	fi
+
+
 #
 # test runs teleport enterprise tests
 #
