Reduce agent recovery time (#3890)
* Reduce agent recovery time

* Add unit test

* Check for agent service health before schedule

* Add ExecStopPost to teleport-upgrader-env.conf

* Trigger upgrade after two consecutive ticks

* Cache version and critical values

* Newline

* Move state dir to /var/lib/teleport/upgrade

* Move state dir to /var/lib/teleport-upgrade

Source-commit: gravitational/teleport.e@3a33f013420ca57189ff05bbad67d57aa26cef69
Source-pull-requests: gravitational/teleport.e#3890

diff --git a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
--- a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
+++ b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
@@ -8,6 +8,9 @@ self_version="v13.0.0-unset"
 # config dir is overridden in tests
 conf_dir="${TELEPORT_UPGRADE_CONFIG:-/etc/teleport-upgrade.d}"
 
+# state_dir contains temporary state values
+state_dir="${TELEPORT_UPGRADE_STATE:-/var/lib/teleport-upgrade}"
+
 # agent conf is the path to teleport.yaml. Is it overidden in tests.
 agent_conf="${TELEPORT_AGENT_CONFIG:-/etc/teleport.yaml}"
 
@@ -91,6 +94,32 @@ get_conf() {
     echo "$normalized_value"
 }
 
+# get_state is a helper for loading values from the state dir. supports very
+# rudimentary comment stripping in order to let us include basic comments in generated
+# state.
+get_state() {
+    state_name=$1
+    default_value=$2
+    full_name="state-$state_name"
+
+    # if file does not exist, use default
+    if ! test -f "$state_dir/$full_name"; then
+        echo "$default_value"
+        return 0
+    fi
+
+    # strip trivially obvious comments, empty lines, and leading/trailing whitespace.
+    normalized_value="$(grep -v -e '^# ' -e '^[[:space:]]*$' <"$state_dir/$full_name" | awk '{$1=$1};1')"
+
+    # if variable is empty post-normalization, use default
+    if [[ -z "$normalized_value" ]]; then
+        echo "$default_value"
+        return 0
+    fi
+
+    echo "$normalized_value"
+}
+
 # get_endpoint chooses which endpoint should be used to get the target version and criticality
 get_endpoint() {
     # if there's a manual override, we honor it
@@ -142,6 +171,9 @@ upgrade_schedule="$(get_conf schedule none)"
 # installer kind is an enum representing the kind of installer to use (apt|yum|zypper|nop).
 installer_kind="$(get_conf installer none)"
 
+# last restart is a timestamp that indicates the last time the teleport service was restarted.
+last_restart="$(get_state last-restart none)"
+
 # log_info prints standard-verbosity messages to stderr.
 log_info() {
     echo "[i] $* [ $(caller | awk '{print $1}') ]" >&2
@@ -169,12 +201,12 @@ pop_state() {
 
     # force use of a common prefix so we don't accidentally delete persistent config values.
     full_name="state-$state_name"
-    state_value="$(get_conf "$full_name" "$default_state_value")"
+    state_value="$(get_state "$state_name" "$default_state_value")"
 
     if [[ "$dry_run" == "yes" ]]; then
         log_debug "preserving previous state value '$state_name' due to dry-run."
     else
-        rm -f "$conf_dir/$full_name"
+        rm -f "$state_dir/$full_name"
     fi
 
     echo "$state_value"
@@ -192,9 +224,9 @@ set_state() {
         return 0
     fi
 
-    mkdir -p "$conf_dir"
+    mkdir -p "$state_dir"
 
-    cat > "$conf_dir/$full_name" <<EOF
+    cat > "$state_dir/$full_name" <<EOF
 # this file is automatically generated by teleport-upgrade.
 # modifications are not persisted.
 $state_value
@@ -267,6 +299,24 @@ schedule_appears_healthy() {
     return 1
 }
 
+# service_appears_healthy checks if the teleport.service is healthy. This is done
+# by checking if the last failed timestamp is within 1 minute.
+service_appears_healthy() {
+    if [[ $last_restart == "none" ]]; then
+        return 0
+    fi
+
+    time_now="$(date +%s)"
+
+    # If the last restart was within the last minute, consider the agent unhealthy.
+    threshold="$(date -d "$last_restart + 1 minute" +%s)"
+    if (( time_now > threshold )); then
+        return 0
+    fi
+
+    log_debug "teleport service appears unhealthy (last_restart within 1 minute)"
+    return 1
+}
 
 # get_current_version gets the current version of the teleport binary. if this
 # operation fails, we assume that teleport is eligible for upgrade.
@@ -334,25 +384,83 @@ upgrade_endpoint_fetch() {
     fi
 }
 
-# get_target_version loads the current value of the /version endpoint.
-get_target_version() {
+# version_fetch fetches the /version endpoint value and caches the value into the
+# specified state.
+version_fetch() {
+    state_name=$1
     if tv_output="$(upgrade_endpoint_fetch version)"; then
         # emit version string with leading 'v' removed if one is present
-        echo "${tv_output#v}"
+        set_state "$state_name" "${tv_output#v}"
         return 0
     fi
-    return 1
+    set_state "$state_name" "none"
+    return 0
 }
 
-# is_critical checks if the /critical endpoint is available and set to 'yes'.
-is_critical() {
+# get_target_version loads the current value of the /version endpoint.
+get_target_version() {
+    state_name="target-version"
+    full_name="state-$state_name"
+
+    # if file does not exist, fetch version endpoint
+    if ! test -f "$state_dir/$full_name"; then
+        version_fetch "$state_name"
+    else
+        # if version value ttl is expired, fetch version endpoint
+        last_modified="$(stat -c  "%y" "$state_dir/$full_name")"
+        ttl="$(date -d "$last_modified + 30 minutes" +%s)"
+        time_now="$(date +%s)"
+
+        if (( time_now > ttl )); then
+            version_fetch "$state_name"
+        fi
+    fi
+
+    target_version="$(get_state "$state_name" none)"
+    echo "$target_version"
+    return 0
+}
+
+# critical_fetch fetches the /critical endpoint value and caches the value into the
+# specified state.
+critical_fetch() {
+    state_name=$1
     if ef_output="$(upgrade_endpoint_fetch critical)"; then
         # perform case-insensitive compare
         if [[ ${ef_output,,} == "yes" ]]; then
+            set_state "$state_name" "yes"
             return 0
         fi
     fi
 
+    set_state "$state_name" "no"
+    return 0
+}
+
+# is_critical checks if the critical value is set to 'yes'.
+is_critical() {
+    state_name="critical"
+    full_name="state-$state_name"
+
+    # if file does not exist, fetch critical endpoint
+    if ! test -f "$state_dir/$full_name"; then
+        critical_fetch "$state_name"
+    else
+        # if critical value ttl is expired, fetch critical endpoint
+        last_modified="$(stat -c "%y" "$state_dir/$full_name")"
+        ttl="$(date -d "$last_modified + 30 minutes" +%s)"
+        time_now="$(date +%s)"
+
+        if (( time_now > ttl )); then
+            critical_fetch "$state_name"
+        fi
+    fi
+
+    # critical indicates whether a critical update is available.
+    critical="$(get_state "$state_name" no)"
+    if [[ "$critical" == "yes" ]]; then
+        return 0
+    fi
     return 1
 }
 
@@ -492,7 +600,7 @@ fi
 
 if [[ "$target_version" == "none" ]]; then
     log_info "version server did not advertise a target version, no upgrade available"
-    exit 0
+    exit 1
 fi
 
 # we compare current version to target version here, but the only effect this comparison has
@@ -524,6 +632,14 @@ if is_critical; then
     log_info "upgrade is marked as critical, will be attempted without checking maintenance window."
 elif in_maintenance_window; then
     log_info "within maintenance window, upgrade will be attempted."
+elif ! service_appears_healthy; then
+    if [[ "$marked_unhealthy" != "yes" ]]; then
+        log_warn "agent is new, or newly unhealthy. marking for potential future upgrade."
+        set_state unhealthy yes
+        exit 0
+    fi
+    restart_mode=restart
+    log_warn "agent was previously marked unhealthy and does not appear recovered, upgrade will be attempted."
 elif ! schedule_appears_healthy; then
     log_warn "agent does not appear to have exported a valid upgrade schedule."
     # lack of healthy upgrade schedule means the agent was either just restarted, or is unhealthy. if
@@ -545,3 +661,7 @@ if ! do_upgrade; then
     log_warn "upgrade attempt failed for $package_name=$target_version."
     exit 1
 fi
+
+# reset state after an upgrade
+pop_state critical no > /dev/null
+pop_state target-version none > /dev/null
