udpater: autodetect proxy endpoint from teleport.yaml (#2793)
Source-commit: gravitational/teleport.e@8116b36bd4a57cf0d91c81ba621bf73467b331d6
Source-pull-requests: gravitational/teleport.e#2793

diff --git a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
--- a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
+++ b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
@@ -8,6 +8,9 @@ self_version="v13.0.0-unset"
 # config dir is overridden in tests
 conf_dir="${TELEPORT_UPGRADE_CONFIG:-/etc/teleport-upgrade.d}"
 
+# agent conf is the path to teleport.yaml. Is it overidden in tests.
+agent_conf="${TELEPORT_AGENT_CONFIG:-/etc/teleport.yaml}"
+
 # note: performing a dry run differs from running with the 'nop' installer
 # in that the 'nop' installer will still modify filesystem state (specifically,
 # it will set/pop the unhealthy marker). dry run will read but not modify the
@@ -61,7 +64,7 @@ get_conf() {
     default_value=$2
     
     # if file does not exist, use default
-    if ! test -f $conf_dir/$conf_name; then
+    if ! test -f "$conf_dir/$conf_name"; then
         echo "$default_value"
         return 0
     fi
@@ -78,8 +81,38 @@ get_conf() {
     echo "$normalized_value"
 }
 
+# get_endpoint chooses which endpoint should be used to get the target version and criticality
+get_endpoint() {
+    # if there's a manual override, we honor it
+    custom_endpoint="$(get_conf endpoint none)"
+    if [[ "$custom_endpoint" != "none" ]]; then
+        echo "$custom_endpoint"
+        return 0
+    fi
+
+    # else, we try to look for the proxy domain in the config file
+    # if there's no teleport config, we use the default
+    if ! test -f "$agent_conf"; then
+        echo $default_endpoint
+        return 0
+    fi
+
+    # we try to parse the teleport config, it it fails we use the default
+    proxy_server="$(grep -oP '^\s+proxy_server:\s*([^\s#]+).*$' "$agent_conf" | sed 's/\s\+proxy_server:\s*\([^[:space:]#]\+\).*/\1/')"
+    if [ -z "$proxy_server" ]; then
+        echo "$default_endpoint"
+        return 0
+    fi
+
+    echo "$proxy_server/v1/webapi/automaticupgrades/channel/stable/cloud"
+}
+
+# default_endpoint is the endpoint used if no endpoint is specified and we cannot detect it
+# from the teleport.yaml config file.
+default_endpoint="updates.releases.teleport.dev/v1/stable/cloud"
+
 # upgrade_endpoint is the base host+path used to load the /version and /critical endpoints
-upgrade_endpoint="$(get_conf endpoint updates.releases.teleport.dev/v1/stable/cloud)"
+upgrade_endpoint="$(get_endpoint)"
 
 # package_name specializes the teleport package name (e.g. teleport|teleport-ent|etc)
 package_name="$(get_conf package teleport)"
@@ -165,8 +198,8 @@ is_insecure_mode() {
         return 1
     fi
 
-    ue_hostport="$(echo $upgrade_endpoint | awk -F/ '{print $1}')"
-    ue_host="$(echo $ue_hostport | awk -F: '{print $1}')"
+    ue_hostport="$(echo "$upgrade_endpoint" | awk -F/ '{print $1}')"
+    ue_host="$(echo "$ue_hostport" | awk -F: '{print $1}')"
 
     if [[ $ue_host != "localhost" ]]; then
         log_warn "refusing to run in insecure mode for non-local endpoint $upgrade_endpoint."
@@ -180,7 +213,7 @@ is_insecure_mode() {
 # <config-dir>/schedule. the schedule file contains pairs of unix timestamps representing
 # the start and end times of maintenance windows.
 in_maintenance_window() {
-    if [[ $upgrade_schedule == "none" ]]; then
+    if [[ "$upgrade_schedule" == "none" ]]; then
         log_debug "cannot check maintenance window (no schedule)."
         return 1
     fi
@@ -188,8 +221,8 @@ in_maintenance_window() {
     time_now="$(date +%s)"
     
     while read line; do
-        start_time="$(echo $line | awk '{print $1}')"
-        end_time="$(echo $line | awk '{print $2}')" 
+        start_time="$(echo "$line" | awk '{print $1}')"
+        end_time="$(echo "$line" | awk '{print $2}')"
 
         if (( time_now > start_time && time_now < end_time )); then
             log_debug "within maintenance window ${start_time} - ${end_time}."
@@ -212,7 +245,7 @@ schedule_appears_healthy() {
     time_now="$(date +%s)"
     
     while read line; do
-        end_time="$(echo $line | awk '{print $2}')" 
+        end_time="$(echo "$line" | awk '{print $2}')"
 
         if (( time_now < end_time )); then
             log_debug "schedule appears healthy (contains future window)"
@@ -397,6 +430,11 @@ marked_unhealthy="$(pop_state unhealthy no)"
 if ! target_version="$(get_target_version)"; then
     log_warn "failed to get target version, cannot proceed with upgrade check."
     exit 1
+fi
+
+if [[ "$target_version" == "none" ]]; then
+  log_info "version server did not advertise a target version, no upgrade available"
+  exit 0
 fi
 
 # we compare current version to target version here, but the only effect this comparison has
