improve unit upgrader
Source-commit: gravitational/teleport.e@74ab6251c8a425ad94db3e763455f374f213f422

diff --git a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
--- a/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
+++ b/e/assets/systemd-unit-upgrader/rootfs/usr/sbin/teleport-upgrade
@@ -2,8 +2,56 @@
 
 set -euo pipefail
 
+self_version="${self_version:-13.0.0}"
 
+
+# config dir is overridden in tests
 conf_dir="${TELEPORT_UPGRADE_CONFIG:-/etc/teleport-upgrade.d}"
+
+# note: performing a dry run differs from running with the 'nop' installer
+# in that the 'nop' installer will still modify filesystem state (specifically,
+# it will set/pop the unhealthy marker). dry run will read but not modify the
+# marker. generally speaking, dry run is intended for use by humans to verify
+# that their installers are correctly configured. the 'nop' installer is intended
+# to be used by tests for confirming the correct behavior of the installer.
+dry_run="yes"
+
+cmd="${1:-none}"
+
+case "$cmd" in
+    run)
+        dry_run="no"
+        ;;
+    dry-run)
+        # this is the default path
+        ;;
+    version)
+        echo "$self_version"
+        exit 0
+        ;;
+    help)
+        cat <<EOF
+USAGE: $0 <command>
+
+Tool for automatic upgrades of Teleport agents.
+
+Commands:
+  run           check for and potentially apply a teleport upgrade.
+  dry-run       check for new teleport version but do not upgrade.
+  version       print the current version of $0.
+  help          show this help text.
+EOF
+        exit 0
+        ;;
+    none)
+        echo "ERROR: missing required command. run '$0 help' to see available commands." >&2
+        exit 1
+        ;;
+    *)
+        echo "ERROR: unknown command '$cmd'. run '$0 help' to see available commands." >&2
+        exit 1
+        ;;
+esac
 
 # get_conf is a helper for loading values from the configuration dir. supports very
 # rudimentary comment stripping in order to let us include basic comments in generated
@@ -30,7 +78,6 @@ get_conf() {
     echo "$normalized_value"
 }
 
-
 # upgrade_endpoint is the base host+path used to load the /version and /critical endpoints
 upgrade_endpoint="$(get_conf endpoint updates.releases.teleport.dev/v1/stable/cloud)"
 
@@ -52,7 +99,6 @@ upgrade_schedule="$(get_conf schedule none)"
 # installer kind is an enum representing the kind of installer to use (apt|yum|nop).
 installer_kind="$(get_conf installer nop)"
 
-
 # log_info prints standard-verbosity messages to stderr.
 log_info() {
     echo "[i] $* [ $(caller | awk '{print $1}') ]" >&2
@@ -71,27 +117,46 @@ log_debug() {
     echo "[d] $* [ $(caller | awk '{print $1}') ]" >&2
 }
 
-# pop_unhealthy_marker reads and then deletes the mark-unhealthy file. we can't distinguish between an
-# unhealthy agent and an agent that was just restarted, so we use the unhealthy marker to ensure that
-# the agent has had at least one 'tick' to try to get itself healthy before we attempt an upgrade.
-pop_unhealthy_marker() {
-    marker_value="$(get_conf mark-unhealthy no)"
-    rm -f "$conf_dir/mark-unhealthy"
-    echo "$marker_value"
+# pop_state reads and then deletes an ephemeral config value. short-lived state values are
+# used to track state between runs and as a mechanism of limiting the impact of potentially
+# risky test configuration options by forcing them to be re-set each run.
+pop_state() {
+    state_name=$1
+    default_state_value=$2
+
+    # force use of a common prefix so we don't accidentally delete persistent config values.
+    full_name="state-$state_name"
+    state_value="$(get_conf "$full_name" "$default_state_value")"
+    
+    if [[ "$dry_run" == "yes" ]]; then
+        log_debug "preserving previous state value '$state_name' due to dry-run."
+    else
+        rm -f "$conf_dir/$full_name"
+    fi
+
+    echo "$state_value"
 }
 
-# set_unhealthy_marker sets the unhealthy marker to 'yes'. includes a comment string to help
-# clarify the nature of the file.
-set_unhealthy_marker() {
+# set_state sets an ephemeral config value. see pop_state for explanation.
+set_state() {
+    state_name=$1
+    state_value=$2
+
+    full_name="state-$state_name"
+
+    if [[ "$dry_run" == "yes" ]]; then
+        log_debug "skipping update of state value '$state_name' due to dry-run."
+        return 0
+    fi
+
     mkdir -p "$conf_dir"
 
-    cat > "$conf_dir/mark-unhealthy" <<EOF
+    cat > "$conf_dir/$full_name" <<EOF
 # this file is automatically generated by teleport-upgrade.
 # modifications are not persisted.
-yes
+$state_value
 EOF
 }
-
 
 # is_insecure_mode returns 0 if the 'insecure' config param was set to 'yes' *and* the
 # upgrade endpoint looks like it points to localhost.
@@ -123,13 +188,8 @@ in_maintenance_window() {
     time_now="$(date +%s)"
     
     while read line; do
-        prefix="$(echo $line | awk '{print $1}')"
-        if [[ "$prefix" != "win" ]]; then
-            continue
-        fi
-
-        start_time="$(echo $line | awk '{print $2}')"
-        end_time="$(echo $line | awk '{print $3}')" 
+        start_time="$(echo $line | awk '{print $1}')"
+        end_time="$(echo $line | awk '{print $2}')" 
 
         if (( time_now > start_time && time_now < end_time )); then
             log_debug "within maintenance window ${start_time} - ${end_time}."
@@ -168,6 +228,20 @@ schedule_appears_healthy() {
 # get_current_version gets the current version of the teleport binary. if this
 # operation fails, we assume that teleport is eligible for upgrade.
 get_current_version() {
+
+    # tests may override the version value. we use pop_state rather than get_conf to load
+    # this value since it would be dangerous to support a persistent config like this.
+    version_override="$(pop_state version-override none)"
+    if [[ "$version_override" != "none" ]]; then
+        # setting version override to 'fail' is used to simulate undiscoverable version
+        if [[ "$version_override" == "fail" ]]; then
+            return 1
+        fi
+
+        echo "$version_override"
+        return 0
+    fi
+
     if cv_output="$(teleport version --raw)"; then
         echo "${cv_output}"
         return 0
@@ -228,10 +302,14 @@ is_critical() {
 
 # do_upgrade invokes the appropriate installer_kind with package_name=target_version.
 do_upgrade() {
+    if [[ "$dry_run" == "yes" ]]; then
+        log_info "skipping install: kind=$installer_kind package=$package_name version=$target_version (dry-run)."
+        return 0
+    fi
     case "$installer_kind" in
         nop)
             log_info "attempting nop install $package_name=$target_version..."
-            echo "nop install $package_name=$target_version"
+            echo "nop-install: $package_name=$target_version"
             return 0
             ;;
         apt)
@@ -265,10 +343,10 @@ do_upgrade() {
 
 log_debug "init: endpoint=$upgrade_endpoint, insecure=$insecure_mode, package=$package_name"
 
-marked_unhealthy="$(pop_unhealthy_marker)"
+marked_unhealthy="$(pop_state unhealthy no)"
 
 if ! target_version="$(get_target_version)"; then
-    log_warn "failed to get target version, cannot proceed with update check."
+    log_warn "failed to get target version, cannot proceed with upgrade check."
     exit 1
 fi
 
@@ -282,21 +360,21 @@ if current_version="$(get_current_version)"; then
         log_info "an upgrade is available ($current_version -> $target_version)"
     fi
 else
-    log_info "failed to detect current version, assuming $target_version to be valid target."
+    log_warn "failed to detect current version, assuming $target_version to be a potential upgrade."
 fi
-
 
 if is_critical; then
     log_info "upgrade is marked as critical, will be attempted without checking maintenance window."
 elif in_maintenance_window; then
     log_info "within maintenance window, upgrade will be attempted."
 elif ! schedule_appears_healthy; then
+    log_warn "agent does not appear to have exported a valid upgrade schedule."
     # lack of healthy upgrade schedule means the agent was either just restarted, or is unhealthy. if
     # we also observed unhealthy state on the previous tick, we take that to mean the problem is
     # persistent, rather than having been caused by a restart.
     if [[ "$marked_unhealthy" != "yes" ]]; then 
-        log_info "agent may be unhealthy. marking for potential future upgrade."
-        set_unhealthy_marker
+        log_warn "agent is new, or newly unhealthy. marking for potential future upgrade."
+        set_state unhealthy yes
         exit 0
     fi
     log_warn "agent was previously marked unhealthy and does not appear recovered, upgrade will be attempted."
