Fixed syntax error in load-gpg-key script (#1144)
Source-commit: gravitational/teleport.e@ace87a2c51f09bb3d3c6f61f00898607b4728b03
Source-pull-requests: gravitational/teleport.e#1144

diff --git a/e/.github/actions/load-gpg-key/action.yaml b/e/.github/actions/load-gpg-key/action.yaml
--- a/e/.github/actions/load-gpg-key/action.yaml
+++ b/e/.github/actions/load-gpg-key/action.yaml
@@ -21,8 +21,8 @@ runs:
         GNUPGHOME: ${{ inputs.gnupghome }}
       run: |
         # Load the GPG key from the input archive
-        [ -n "$GNUPGHOME" ] || { echo "GNUPGHOME input is unset or empty, aborting"; exit 1 }
-        [ -n "$GPG_SIGNING_ARCHIVE" ] || { echo "GPG signing archive input is unset or empty, aborting"; exit 1 }
+        [ -n "$GNUPGHOME" ] || { echo "GNUPGHOME input is unset or empty, aborting"; exit 1; }
+        [ -n "$GPG_SIGNING_ARCHIVE" ] || { echo "GPG signing archive input is unset or empty, aborting"; exit 1; }
 
         echo "Extracting the GPG signing key to GNUPGHOME at $GNUPGHOME"
         mkdir -pv -m0700 "$GNUPGHOME"
