Release the Terraform provider for Windows (#7202)
* adding a windows-release cross build, adding logic to only tar on non-windows builds, this will generate a .exe

* reverting os to default to linux, as windows build will run on a linux box

* adding smoke test for uploaded .exe and manifest

* pointing smoke test to master

* updated existing smoke test to be able to handle windows runs, build plugins now also handles tar .exe files

* typo, missing trailing slash

* pointing some test to master after successful build

* Apply suggestions from code review

Co-authored-by: fheinecke <23390735+fheinecke@users.noreply.github.com>

* updating cross build invocation to call release instead of windows-release

* updating smoke test for CI build test

* pointing smoke test back to master branch after successful build

* addressing PR comments

* pointing smoke test to current branch for CI build

* updating extraction of os and arch from filename logic

* normalizing manifest, after local testing this i the least intrusuive way to handle .exe

* adding normalize step for bin.tar

* handling error from ci, this change should handle all steps

* fixing bug, the windows binary terraform-provider-teleport.exe was being uploaded when collecting files, which was breaking parsing

* comment cannot be added in find command multiline

* poting smoke test for windows plugin back to master branch after successful build

* Update .github/actions/smoke-test-plugin-tarballs/action.yaml

Co-authored-by: fheinecke <23390735+fheinecke@users.noreply.github.com>

---------

Co-authored-by: fheinecke <23390735+fheinecke@users.noreply.github.com>

Source-commit: gravitational/teleport.e@e1731703a38a041b0f35b3cb1fa5767d8709f3bc
Source-pull-requests: gravitational/teleport.e#7202

diff --git a/e/.github/actions/smoke-test-plugin-tarballs/action.yaml b/e/.github/actions/smoke-test-plugin-tarballs/action.yaml
--- a/e/.github/actions/smoke-test-plugin-tarballs/action.yaml
+++ b/e/.github/actions/smoke-test-plugin-tarballs/action.yaml
@@ -76,9 +76,13 @@ runs:
         TARGET: ${{ inputs.target }}
       run: |
         aws s3 sync "$BUCKET_DIR_URI" "$LOCAL_ARTIFACTS_PATH/" \
-        --exclude "*" --include "*$TARGET-bin.tar.gz"
+          --exclude "*" \
+          --include "*.exe" \
+          --include "*.exe.manifest" \
+          --include "*$TARGET-bin.tar.gz"
 
-    - name: Verify Plugin Tarballs
+    - name: Verify Plugin Tarballs (macOS/Linux)
+      if: ${{ inputs.target != 'windows-amd64' }}
       shell: bash
       env:
         LOCAL_ARTIFACTS_PATH: /tmp/artifacts
@@ -119,4 +123,26 @@ runs:
           echo "::error title=Smoke terraform-provider-teleport::terraform-provider-teleport-$ARTIFACT_TAG failed to run for $TARGET"
           echo "* :x: terraform-provider-teleport" >> "$GITHUB_STEP_SUMMARY"
         fi
+        exit $CODE
+
+    - name: Verify downloaded .exe plugin artifacts
+      shell: bash
+      if: ${{ inputs.target == 'windows-amd64' }}
+      env:
+        LOCAL_ARTIFACTS_PATH: /tmp/artifacts
+        VERSION: ${{ inputs.version }}
+      run: |
+        echo "## Verifying .exe plugin artifacts for v$VERSION" | tee -a "$GITHUB_STEP_SUMMARY"
+        CODE=0
+
+        TF_PROVIDER_EXE="terraform-provider-teleport-v${VERSION}-windows-amd64.exe"
+
+        if [[ -f "$LOCAL_ARTIFACTS_PATH/$TF_PROVIDER_EXE" ]]; then
+          echo "* Found $TF_PROVIDER_EXE"  | tee -a "$GITHUB_STEP_SUMMARY"
+        else
+          echo "::error title=Missing EXE::$TF_PROVIDER_EXE not found"
+          echo "* Missing $TF_PROVIDER_EXE"  | tee -a "$GITHUB_STEP_SUMMARY"
+        CODE=1
+        fi
+
         exit $CODE
